local addonName, SGJ = ...

-- 2. INITIALIZE DB
SGJ.DungeonDB = SGJ.DungeonDB or {}

-- ============================================================
-- TBC DUNGEONS
-- ============================================================

SGJ.DungeonDB["HellfireRamparts"] = {
    [24044] = { name = "Shadowrend Longblade", source = "Watchkeeper Gargolmar", slot = "Main Hand", type = "One-Handed Sword", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24021] = { name = "Light-Touched Breastplate", source = "Watchkeeper Gargolmar", slot = "Chest", type = "Plate Armor", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24022] = { name = "Scale Leggings of the Skirmisher", source = "Watchkeeper Gargolmar", slot = "Legs", type = "Mail Armor", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24023] = { name = "Bracers of Finesse", source = "Watchkeeper Gargolmar", slot = "Wrist", type = "Leather Armor", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24024] = { name = "Pauldrons of Arcane Rage", source = "Watchkeeper Gargolmar", slot = "Shoulder", type = "Cloth Armor", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24044] = { name = "Hellreaver", source = "Reinforced Fel Iron Chest", slot = "Two-Hand", type = "Polearm", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24020] = { name = "Band of Renewal", source = "Reinforced Fel Iron Chest", slot = "Finger", type = "Ring", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24046] = { name = "Kilt of Rolling Thunders", source = "Reinforced Fel Iron Chest", slot = "Legs", type = "Mail Armor", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24045] = { name = "Shifting Sash of Midnight", source = "Reinforced Fel Iron Chest", slot = "Waist", type = "Leather Armor", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24063] = { name = "Ironsole Clompers", source = "Reinforced Fel Iron Chest", slot = "Feet", type = "Plate Armor", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24064] = { name = "Crystalfire Staff", source = "Omor the Unscarred", slot = "Two-Hand", type = "Staff", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24069] = { name = "Garrote-String Necklace", source = "Omor the Unscarred", slot = "Neck", type = "Amulet", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24073] = { name = "Lifegiver Britches", source = "Reinforced Fel Iron Chest", slot = "Legs", type = "Cloth Armor", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24083] = { name = "Bloodstained Ravager Gauntlets", source = "Omor the Unscarred", slot = "Hands", type = "Mail Armor", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24090] = { name = "Tenacious Defender", source = "Omor the Unscarred", slot = "Waist", type = "Plate Armor", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24091] = { name = "Heart Fire Warhammer", source = "Omor the Unscarred", slot = "Two-Hand", type = "Two-Handed Mace", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24094] = { name = "Heartblood Prayer Beads", source = "Omor the Unscarred", slot = "Neck", type = "Amulet", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24096] = { name = "Mok'Nathal Wildercloak", source = "Reinforced Fel Iron Chest", slot = "Back", type = "Cloak", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24150] = { name = "Mok'Nathal Clan Ring", source = "Reinforced Fel Iron Chest", slot = "Finger", type = "Ring", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24151] = { name = "Witching Band", source = "Reinforced Fel Iron Chest", slot = "Finger", type = "Ring", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24154] = { name = "Ursol's Claw", source = "Reinforced Fel Iron Chest", slot = "Two-Hand", type = "Staff", zone = "Hellfire Ramparts", reqLevel = 60 }
}

SGJ.DungeonDB["BloodFurnace"] = {
    [24384] = { name = "Diamond-Core Sledgemace", source = "The Maker", slot = "Main Hand", type = "One-Handed Mace", zone = "The Blood Furnace", reqLevel = 61 },
    [24385] = { name = "Pendant of Battle-Lust", source = "The Maker", slot = "Neck", type = "Amulet", zone = "The Blood Furnace", reqLevel = 61 },
    [24386] = { name = "Libram of Saints Departed", source = "The Maker", slot = "Relic", type = "Libram", zone = "The Blood Furnace", reqLevel = 61 },
    [24387] = { name = "Ironblade Gauntlets", source = "The Maker", slot = "Hands", type = "Plate Armor", zone = "The Blood Furnace", reqLevel = 61 },
    [24388] = { name = "Girdle of the Gale Storm", source = "The Maker", slot = "Waist", type = "Mail Armor", zone = "The Blood Furnace", reqLevel = 61 },
    [24389] = { name = "Legion Blunderbuss", source = "Broggok", slot = "Ranged", type = "Gun", zone = "The Blood Furnace", reqLevel = 61 },
    [24390] = { name = "Auslese's Light Channeler", source = "Broggok", slot = "Trinket", type = "Trinket", zone = "The Blood Furnace", reqLevel = 61 },
    [24391] = { name = "Kilt of the Night Strider", source = "Broggok", slot = "Legs", type = "Leather Armor", zone = "The Blood Furnace", reqLevel = 61 },
    [24392] = { name = "Arcing Bracers", source = "Broggok", slot = "Wrist", type = "Cloth Armor", zone = "The Blood Furnace", reqLevel = 61 },
    [24393] = { name = "Bloody Surgeon's Mitts", source = "Broggok", slot = "Hands", type = "Cloth Armor", zone = "The Blood Furnace", reqLevel = 61 },
    [24394] = { name = "Warsong Howling Axe", source = "Keli'dan the Breaker", slot = "Two-Hand", type = "Two-Handed Axe", zone = "The Blood Furnace", reqLevel = 61 },
    [24395] = { name = "Mindfire Waistband", source = "Keli'dan the Breaker", slot = "Waist", type = "Cloth Armor", zone = "The Blood Furnace", reqLevel = 61 },
    [24396] = { name = "Vest of Vengeance", source = "Keli'dan the Breaker", slot = "Chest", type = "Leather Armor", zone = "The Blood Furnace", reqLevel = 61 },
    [24397] = { name = "Raiments of Divine Authority", source = "Keli'dan the Breaker", slot = "Chest", type = "Cloth Armor", zone = "The Blood Furnace", reqLevel = 61 },
    [24398] = { name = "Mantle of the Dusk-Dweller", source = "Keli'dan the Breaker", slot = "Shoulder", type = "Leather Armor", zone = "The Blood Furnace", reqLevel = 61 }
}

SGJ.DungeonDB["SlavePens"] = {
    [24356] = { name = "Wastewalker Shiv", source = "Mennu the Betrayer", slot = "Main Hand", type = "Dagger", zone = "The Slave Pens", reqLevel = 62 },
    [24357] = { name = "Vest of Living Lightning", source = "Mennu the Betrayer", slot = "Chest", type = "Mail Armor", zone = "The Slave Pens", reqLevel = 62 },
    [24359] = { name = "Princely Reign Leggings", source = "Mennu the Betrayer", slot = "Legs", type = "Cloth Armor", zone = "The Slave Pens", reqLevel = 62 },
    [24360] = { name = "Tracker's Belt", source = "Mennu the Betrayer", slot = "Waist", type = "Mail Armor", zone = "The Slave Pens", reqLevel = 62 },
    [24361] = { name = "Spellfire Longsword", source = "Mennu the Betrayer", slot = "Main Hand", type = "One-Handed Sword", zone = "The Slave Pens", reqLevel = 62 },
    [24362] = { name = "Spore-Soaked Vaneer", source = "Quagmirran", slot = "Back", type = "Cloak", zone = "The Slave Pens", reqLevel = 62 },
    [24363] = { name = "Unscarred Breastplate", source = "Quagmirran", slot = "Chest", type = "Plate Armor", zone = "The Slave Pens", reqLevel = 62 },
    [24364] = { name = "Azureplate Greaves", source = "Quagmirran", slot = "Legs", type = "Plate Armor", zone = "The Slave Pens", reqLevel = 62 },
    [24365] = { name = "Deft Handguards", source = "Quagmirran", slot = "Hands", type = "Leather Armor", zone = "The Slave Pens", reqLevel = 62 },
    [24366] = { name = "Scorpid-Sting Mantle", source = "Quagmirran", slot = "Shoulder", type = "Mail Armor", zone = "The Slave Pens", reqLevel = 62 },
    [24376] = { name = "Runed Fungalcap", source = "Rokmar the Crackler", slot = "Trinket", type = "Trinket", zone = "The Slave Pens", reqLevel = 62 },
    [24378] = { name = "Coilfang Hammer of Renewal", source = "Rokmar the Crackler", slot = "Main Hand", type = "One-Handed Mace", zone = "The Slave Pens", reqLevel = 62 },
    [24379] = { name = "Bogstrok Scale Cloak", source = "Rokmar the Crackler", slot = "Back", type = "Cloak", zone = "The Slave Pens", reqLevel = 62 },
    [24380] = { name = "Calming Spore Reed", source = "Rokmar the Crackler", slot = "Ranged", type = "Wand", zone = "The Slave Pens", reqLevel = 62 },
    [24381] = { name = "Coilfang Needler", source = "Rokmar the Crackler", slot = "Ranged", type = "Crossbow", zone = "The Slave Pens", reqLevel = 62 }
}
		
SGJ.DungeonDB["Underbog"] = {
    [27743] = { name = "Girdle of Living Flame", source = "Hungarfen", slot = "Waist", type = "Mail Armor", zone = "The Underbog", reqLevel = 70 },
    [27744] = { name = "Idol of Ursoc", source = "Hungarfen", slot = "Relic", type = "Idol", zone = "The Underbog", reqLevel = 70 },
    [27745] = { name = "Hungarhide Gauntlets", source = "Hungarfen", slot = "Hands", type = "Mail Armor", zone = "The Underbog", reqLevel = 70 },
    [27746] = { name = "Arcanium Signet Bands", source = "Hungarfen", slot = "Wrist", type = "Cloth Armor", zone = "The Underbog", reqLevel = 70 },
    [27747] = { name = "Boggspine Knuckles", source = "Hungarfen", slot = "Off Hand", type = "Fist Weapon", zone = "The Underbog", reqLevel = 70 },
    [27748] = { name = "Cassock of the Loyal", source = "Hungarfen", slot = "Legs", type = "Plate Armor", zone = "The Underbog", reqLevel = 70 },
    [27755] = { name = "Girdle of Gallantry", source = "Ghaz'an", slot = "Waist", type = "Plate Armor", zone = "The Underbog", reqLevel = 70 },
    [27757] = { name = "Greatstaff of the Leviathan", source = "Ghaz'an", slot = "Two-Hand", type = "Staff", zone = "The Underbog", reqLevel = 70 },
    [27758] = { name = "Hydra-fang Necklace", source = "Ghaz'an", slot = "Neck", type = "Amulet", zone = "The Underbog", reqLevel = 70 },
    [27759] = { name = "Headdress of the Tides", source = "Ghaz'an", slot = "Head", type = "Mail Armor", zone = "The Underbog", reqLevel = 70 },
    [27760] = { name = "Dunewind Sash", source = "Ghaz'an", slot = "Waist", type = "Leather Armor", zone = "The Underbog", reqLevel = 70 },
    [27761] = { name = "Ring of the Shadow Deeps", source = "Ghaz'an", slot = "Finger", type = "Ring", zone = "The Underbog", reqLevel = 70 },
    [27768] = { name = "Oracle Belt of Timeless Mystery", source = "The Black Stalker", slot = "Waist", type = "Cloth Armor", zone = "The Underbog", reqLevel = 70 },
    [27769] = { name = "Endbringer", source = "The Black Stalker", slot = "Two-Hand", type = "Two-Handed Sword", zone = "The Underbog", reqLevel = 70 },
    [27770] = { name = "Argussian Compass", source = "The Black Stalker", slot = "Trinket", type = "Trinket", zone = "The Underbog", reqLevel = 70 },
    [27771] = { name = "Doomplate Shoulderguards", source = "The Black Stalker", slot = "Shoulder", type = "Plate Armor", zone = "The Underbog", reqLevel = 70 },
    [27772] = { name = "Stormshield of Renewal", source = "The Black Stalker", slot = "Shield", type = "Shield", zone = "The Underbog", reqLevel = 70 },
    [27773] = { name = "Barbaric Legstraps", source = "The Black Stalker", slot = "Legs", type = "Mail Armor", zone = "The Underbog", reqLevel = 70 },
    [27779] = { name = "Bone Chain Necklace", source = "The Black Stalker", slot = "Neck", type = "Amulet", zone = "The Underbog", reqLevel = 70 },
    [27780] = { name = "Ring of Fabled Hope", source = "The Black Stalker", slot = "Finger", type = "Ring", zone = "The Underbog", reqLevel = 70 },
    [27781] = { name = "Demonfang Ritual Helm", source = "The Black Stalker", slot = "Head", type = "Cloth Armor", zone = "The Underbog", reqLevel = 70 },
    [27896] = { name = "Alembic of Infernal Power", source = "The Black Stalker", slot = "Trinket", type = "Trinket", zone = "The Underbog", reqLevel = 70 },
    [27907] = { name = "Mana-Etched Pantaloons", source = "The Black Stalker", slot = "Legs", type = "Cloth Armor", zone = "The Underbog", reqLevel = 70 },
    [27938] = { name = "Savage Mask of the Lynx Lord", source = "The Black Stalker", slot = "Head", type = "Leather Armor", zone = "The Underbog", reqLevel = 70 },
    [29265] = { name = "Barkchip Boots", source = "The Black Stalker", slot = "Feet", type = "Leather Armor", zone = "The Underbog", reqLevel = 70 },
    [29350] = { name = "The Black Stalk", source = "The Black Stalker", slot = "Ranged", type = "Wand", zone = "The Underbog", reqLevel = 70 },
    [30541] = { name = "Stormsong Kilt", source = "The Black Stalker", slot = "Legs", type = "Mail Armor", zone = "The Underbog", reqLevel = 70 },
    [32081] = { name = "Eye of the Stalker", source = "The Black Stalker", slot = "Finger", type = "Ring", zone = "The Underbog", reqLevel = 70 },
    [24413] = { name = "Totem of the Thunderhead", source = "Hungarfen", slot = "Relic", type = "Totem", zone = "The Underbog", reqLevel = 63 },
    [24450] = { name = "Manaspark Gloves", source = "Hungarfen", slot = "Hands", type = "Cloth Armor", zone = "The Underbog", reqLevel = 63 },
    [24451] = { name = "Lykul Bloodbands", source = "Hungarfen", slot = "Wrist", type = "Mail Armor", zone = "The Underbog", reqLevel = 63 },
    [24452] = { name = "Starlight Gauntlets", source = "Hungarfen", slot = "Hands", type = "Leather Armor", zone = "The Underbog", reqLevel = 63 },
    [24453] = { name = "Zangartooth Shortblade", source = "Swamplord Musel'ek", slot = "Main Hand", type = "Dagger", zone = "The Underbog", reqLevel = 63 },
    [24454] = { name = "Cloak of Enduring Swiftness", source = "Swamplord Musel'ek", slot = "Back", type = "Cloak", zone = "The Underbog", reqLevel = 63 },
    [24455] = { name = "Tunic of the Nightwatcher", source = "Swamplord Musel'ek", slot = "Chest", type = "Leather Armor", zone = "The Underbog", reqLevel = 63 },
    [24456] = { name = "Greaves of the Iron Guardian", source = "Swamplord Musel'ek", slot = "Legs", type = "Plate Armor", zone = "The Underbog", reqLevel = 63 },
    [24457] = { name = "Truth Bearer Shoulderguards", source = "Swamplord Musel'ek", slot = "Shoulder", type = "Plate Armor", zone = "The Underbog", reqLevel = 63 },
    [24458] = { name = "Studded Girdle of Virtue", source = "Ghaz'an", slot = "Waist", type = "Plate Armor", zone = "The Underbog", reqLevel = 63 },
    [24459] = { name = "Cloak of Healing Rays", source = "Ghaz'an", slot = "Back", type = "Cloak", zone = "The Underbog", reqLevel = 63 },
    [24460] = { name = "Talisman of Tenacity", source = "Ghaz'an", slot = "Neck", type = "Amulet", zone = "The Underbog", reqLevel = 63 },
    [24461] = { name = "Hatebringer", source = "Ghaz'an", slot = "Two-Hand", type = "Two-Handed Mace", zone = "The Underbog", reqLevel = 63 },
    [24462] = { name = "Luminous Pearls of Insight", source = "Ghaz'an", slot = "Neck", type = "Amulet", zone = "The Underbog", reqLevel = 63 },
    [24463] = { name = "Pauldrons of Brute Force", source = "The Black Stalker", slot = "Shoulder", type = "Plate Armor", zone = "The Underbog", reqLevel = 63 },
    [24464] = { name = "The Stalker's Fangs", source = "The Black Stalker", slot = "One-Hand", type = "Dagger", zone = "The Underbog", reqLevel = 63 },
    [24465] = { name = "Shamblehide Chestguard", source = "The Black Stalker", slot = "Chest", type = "Mail Armor", zone = "The Underbog", reqLevel = 63 },
    [24466] = { name = "Skulldugger's Leggings", source = "The Black Stalker", slot = "Legs", type = "Leather Armor", zone = "The Underbog", reqLevel = 63 },
    [24481] = { name = "Robes of the Augurer", source = "The Black Stalker", slot = "Chest", type = "Cloth Armor", zone = "The Underbog", reqLevel = 63 }
}
		
SGJ.DungeonDB["ManaTombs"] = {
    [25939] = { name = "Voidfire Wand", source = "Pandemonius", slot = "Ranged", type = "Wand", zone = "Mana-Tombs", reqLevel = 64 },
    [25940] = { name = "Idol of the Claw", source = "Pandemonius", slot = "Relic", type = "Idol", zone = "Mana-Tombs", reqLevel = 64 },
    [25941] = { name = "Boots of the Outlander", source = "Pandemonius", slot = "Feet", type = "Mail Armor", zone = "Mana-Tombs", reqLevel = 64 },
    [25942] = { name = "Faith Bearer's Gauntlets", source = "Pandemonius", slot = "Hands", type = "Plate Armor", zone = "Mana-Tombs", reqLevel = 64 },
    [25943] = { name = "Creepjacker", source = "Pandemonius", slot = "Main Hand", type = "Fist Weapon", zone = "Mana-Tombs", reqLevel = 64 },
    [25944] = { name = "Shaarde the Greater", source = "Tavarok", slot = "Two-Hand", type = "Two-Handed Sword", zone = "Mana-Tombs", reqLevel = 64 },
    [25945] = { name = "Cloak of Revival", source = "Tavarok", slot = "Back", type = "Cloak", zone = "Mana-Tombs", reqLevel = 64 },
    [25946] = { name = "Nethershade Boots", source = "Tavarok", slot = "Feet", type = "Leather Armor", zone = "Mana-Tombs", reqLevel = 64 },
    [25947] = { name = "Lightning-Rod Pauldrons", source = "Tavarok", slot = "Shoulder", type = "Mail Armor", zone = "Mana-Tombs", reqLevel = 64 },
    [25950] = { name = "Staff of Polarities", source = "Tavarok", slot = "Two-Hand", type = "Staff", zone = "Mana-Tombs", reqLevel = 64 },
    [25952] = { name = "Scimitar of the Nexus-Stalkers", source = "Tavarok", slot = "One-Hand", type = "One-Handed Sword", zone = "Mana-Tombs", reqLevel = 64 },
    [25953] = { name = "Ethereal Warp-Bow", source = "Nexus-Prince Shaffar", slot = "Ranged", type = "Bow", zone = "Mana-Tombs", reqLevel = 64 },
    [25954] = { name = "Sigil of Shaffar", source = "Nexus-Prince Shaffar", slot = "Neck", type = "Amulet", zone = "Mana-Tombs", reqLevel = 64 },
    [25955] = { name = "Mask of the Howling Storm", source = "Nexus-Prince Shaffar", slot = "Head", type = "Mail Armor", zone = "Mana-Tombs", reqLevel = 64 },
    [25956] = { name = "Nexus-Bracers of Vigor", source = "Nexus-Prince Shaffar", slot = "Wrist", type = "Plate Armor", zone = "Mana-Tombs", reqLevel = 64 },
    [25957] = { name = "Ethereal Boots of the Skystrider", source = "Nexus-Prince Shaffar", slot = "Feet", type = "Cloth Armor", zone = "Mana-Tombs", reqLevel = 64 },
    [25962] = { name = "Longstrider's Loop", source = "Nexus-Prince Shaffar", slot = "Finger", type = "Ring", zone = "Mana-Tombs", reqLevel = 64 },
    [28166] = { name = "Shield of the Void", source = "Pandemonius", slot = "Shield", type = "Shield", zone = "Mana-Tombs", reqLevel = 64 }
}

SGJ.DungeonDB["AuchenaiCrypts"] = {
    [25964] = { name = "Shaarde the Lesser", source = "Shirrak the Dead Watcher", slot = "Main Hand", type = "One-Handed Sword", zone = "Auchenai Crypts", reqLevel = 65 },
    [26055] = { name = "Oculus of the Hidden Eye", source = "Shirrak the Dead Watcher", slot = "Trinket", type = "Trinket", zone = "Auchenai Crypts", reqLevel = 65 },
    [27408] = { name = "Hope Bearer Helm", source = "Shirrak the Dead Watcher", slot = "Head", type = "Plate Armor", zone = "Auchenai Crypts", reqLevel = 65 },
    [27409] = { name = "Raven-Heart Headdress", source = "Shirrak the Dead Watcher", slot = "Head", type = "Leather Armor", zone = "Auchenai Crypts", reqLevel = 65 },
    [27410] = { name = "Collar of Command", source = "Shirrak the Dead Watcher", slot = "Head", type = "Cloth Armor", zone = "Auchenai Crypts", reqLevel = 65 },
    [27411] = { name = "Slippers of Serenity", source = "Exarch Maladaar", slot = "Feet", type = "Cloth Armor", zone = "Auchenai Crypts", reqLevel = 65 },
    [27412] = { name = "Ironstaff of Regeneration", source = "Exarch Maladaar", slot = "Two-Hand", type = "Staff", zone = "Auchenai Crypts", reqLevel = 65 },
    [27413] = { name = "Ring of the Exarchs", source = "Exarch Maladaar", slot = "Finger", type = "Ring", zone = "Auchenai Crypts", reqLevel = 65 },
    [27414] = { name = "Mok'Nathal Beast-Mask", source = "Exarch Maladaar", slot = "Head", type = "Mail Armor", zone = "Auchenai Crypts", reqLevel = 65 },
    [27415] = { name = "Darkguard Face Mask", source = "Exarch Maladaar", slot = "Head", type = "Leather Armor", zone = "Auchenai Crypts", reqLevel = 65 },
    [27416] = { name = "Fetish of the Fallen", source = "Exarch Maladaar", slot = "Trinket", type = "Trinket", zone = "Auchenai Crypts", reqLevel = 65 }
}

SGJ.DungeonDB["OldHillsbrad"] = {
    [27417] = { name = "Ravenwing Pauldrons", source = "Lieutenant Drake", slot = "Shoulder", type = "Leather Armor", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27418] = { name = "Stormreaver Shadow-Kilt", source = "Lieutenant Drake", slot = "Legs", type = "Cloth Armor", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27420] = { name = "Uther's Ceremonial Warboots", source = "Lieutenant Drake", slot = "Feet", type = "Plate Armor", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27423] = { name = "Cloak of Impulsiveness", source = "Lieutenant Drake", slot = "Back", type = "Cloak", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27424] = { name = "Amani Venom-Axe", source = "Captain Skarloc", slot = "One-Hand", type = "One-Handed Axe", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27426] = { name = "Northshire Battlemace", source = "Captain Skarloc", slot = "Main Hand", type = "One-Handed Mace", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27427] = { name = "Durotan's Battle Harness", source = "Captain Skarloc", slot = "Chest", type = "Plate Armor", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27428] = { name = "Stormfront Gauntlets", source = "Captain Skarloc", slot = "Hands", type = "Mail Armor", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27430] = { name = "Scaled Greaves of Patience", source = "Captain Skarloc", slot = "Legs", type = "Mail Armor", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27431] = { name = "Time-Shifted Dagger", source = "Epoch Hunter", slot = "Main Hand", type = "Dagger", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27432] = { name = "Broxigar's Ring of Valor", source = "Epoch Hunter", slot = "Finger", type = "Ring", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27433] = { name = "Pauldrons of Sufferance", source = "Epoch Hunter", slot = "Shoulder", type = "Cloth Armor", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27434] = { name = "Mantle of Perenolde", source = "Epoch Hunter", slot = "Shoulder", type = "Leather Armor", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27436] = { name = "Iron Band of the Unbreakable", source = "Lieutenant Drake", slot = "Finger", type = "Ring", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27440] = { name = "Diamond Prism of Recurrence", source = "Epoch Hunter", slot = "Neck", type = "Amulet", zone = "Old Hillsbrad Foothills", reqLevel = 66 }
}

SGJ.DungeonDB["SethekkHalls"] = {
    [27776] = { name = "Shoulderpads of Assassination", source = "Talon King Ikiss", slot = "Shoulder", type = "Leather Armor", zone = "Sethekk Halls", reqLevel = 70 },
    [27838] = { name = "Incanter's Trousers", source = "Talon King Ikiss", slot = "Legs", type = "Cloth Armor", zone = "Sethekk Halls", reqLevel = 70 },
    [27875] = { name = "Hallowed Trousers", source = "Talon King Ikiss", slot = "Legs", type = "Cloth Armor", zone = "Sethekk Halls", reqLevel = 70 },
    [27914] = { name = "Moonstrider Boots", source = "Darkweaver Syth", slot = "Feet", type = "Leather Armor", zone = "Sethekk Halls", reqLevel = 68 },
    [27915] = { name = "Sky-Hunter Swift Boots", source = "Darkweaver Syth", slot = "Feet", type = "Mail Armor", zone = "Sethekk Halls", reqLevel = 68 },
    [27916] = { name = "Sethekk Feather-Darts", source = "Darkweaver Syth", slot = "Thrown", type = "Thrown Weapon", zone = "Sethekk Halls", reqLevel = 68 },
    [27917] = { name = "Libram of the Eternal Rest", source = "Darkweaver Syth", slot = "Relic", type = "Libram", zone = "Sethekk Halls", reqLevel = 68 },
    [27918] = { name = "Bands of Syth", source = "Darkweaver Syth", slot = "Wrist", type = "Plate Armor", zone = "Sethekk Halls", reqLevel = 68 },
    [27919] = { name = "Light-Woven Slippers", source = "Darkweaver Syth", slot = "Feet", type = "Cloth Armor", zone = "Sethekk Halls", reqLevel = 68 },
    [27925] = { name = "Ravenclaw Band", source = "Talon King Ikiss", slot = "Finger", type = "Ring", zone = "Sethekk Halls", reqLevel = 68 },
    [27936] = { name = "Greaves of Desolation", source = "Talon King Ikiss", slot = "Legs", type = "Mail Armor", zone = "Sethekk Halls", reqLevel = 68 },
    [27946] = { name = "Avian Cloak of Feathers", source = "Talon King Ikiss", slot = "Back", type = "Cloak", zone = "Sethekk Halls", reqLevel = 68 },
    [27948] = { name = "Trousers of Oblivion", source = "Talon King Ikiss", slot = "Legs", type = "Cloth Armor", zone = "Sethekk Halls", reqLevel = 68 },
    [27980] = { name = "Terokk's Nightmace", source = "Talon King Ikiss", slot = "One-Hand", type = "One-Handed Mace", zone = "Sethekk Halls", reqLevel = 68 },
    [27981] = { name = "Sethekk Oracle Cloak", source = "Talon King Ikiss", slot = "Back", type = "Cloak", zone = "Sethekk Halls", reqLevel = 68 },
    [27985] = { name = "Deathforge Girdle", source = "Talon King Ikiss", slot = "Waist", type = "Plate Armor", zone = "Sethekk Halls", reqLevel = 68 },
    [27986] = { name = "Crow Wing Reaper", source = "Talon King Ikiss", slot = "Two-Hand", type = "Two-Handed Axe", zone = "Sethekk Halls", reqLevel = 68 },
    [31285] = { name = "Chestguard of the Talon", source = "Zone Drop", slot = "Chest", type = "Leather Armor", zone = "Sethekk Halls", reqLevel = 68 }
}

SGJ.DungeonDB["BlackMorass"] = {
    [27509] = { name = "Handgrips of Assassination", source = "Aeonus", slot = "Hands", type = "Leather Armor", zone = "The Black Morass", reqLevel = 70 },
    [27839] = { name = "Legplates of the Righteous", source = "Aeonus", slot = "Legs", type = "Plate Armor", zone = "The Black Morass", reqLevel = 70 },
    [27873] = { name = "Moonglade Pants", source = "Aeonus", slot = "Legs", type = "Leather Armor", zone = "The Black Morass", reqLevel = 70 },
    [27977] = { name = "Legplates of the Bold", source = "Aeonus", slot = "Legs", type = "Plate Armor", zone = "The Black Morass", reqLevel = 68 },
    [27987] = { name = "Melmorta's Twilight Longbow", source = "Chrono Lord Deja", slot = "Ranged", type = "Bow", zone = "The Black Morass", reqLevel = 68 },
    [27988] = { name = "Burnoose of Shifting Ages", source = "Chrono Lord Deja", slot = "Back", type = "Cloak", zone = "The Black Morass", reqLevel = 68 },
    [27993] = { name = "Mask of Inner Fire", source = "Chrono Lord Deja", slot = "Head", type = "Mail Armor", zone = "The Black Morass", reqLevel = 68 },
    [27994] = { name = "Mantle of Three Terrors", source = "Chrono Lord Deja", slot = "Shoulder", type = "Cloth Armor", zone = "The Black Morass", reqLevel = 68 },
    [27995] = { name = "Sun-Gilded Shouldercaps", source = "Chrono Lord Deja", slot = "Shoulder", type = "Leather Armor", zone = "The Black Morass", reqLevel = 68 },
    [27996] = { name = "Ring of Spiritual Precision", source = "Chrono Lord Deja", slot = "Finger", type = "Ring", zone = "The Black Morass", reqLevel = 68 },
    [28033] = { name = "Epoch-Mender", source = "Temporus", slot = "Two-Hand", type = "Staff", zone = "The Black Morass", reqLevel = 68 },
    [28034] = { name = "Hourglass of the Unraveller", source = "Temporus", slot = "Trinket", type = "Trinket", zone = "The Black Morass", reqLevel = 68 },
    [28184] = { name = "Millennium Blade", source = "Temporus", slot = "One-Hand", type = "One-Handed Sword", zone = "The Black Morass", reqLevel = 68 },
    [28185] = { name = "Khadgar's Kilt of Abjuration", source = "Temporus", slot = "Legs", type = "Cloth Armor", zone = "The Black Morass", reqLevel = 68 },
    [28186] = { name = "Laughing Skull Battle-Harness", source = "Temporus", slot = "Chest", type = "Mail Armor", zone = "The Black Morass", reqLevel = 68 },
    [28187] = { name = "Star-Heart Lamp", source = "Temporus", slot = "Held In Off-hand", type = "Off-hand Frill", zone = "The Black Morass", reqLevel = 68 },
    [28188] = { name = "Bloodfire Greatstaff", source = "Aeonus", slot = "Two-Hand", type = "Staff", zone = "The Black Morass", reqLevel = 70 },
    [28189] = { name = "Latro's Shifting Sword", source = "Aeonus", slot = "One-Hand", type = "One-Handed Sword", zone = "The Black Morass", reqLevel = 70 },
    [28190] = { name = "Scarab of the Infinite Cycle", source = "Aeonus", slot = "Trinket", type = "Trinket", zone = "The Black Morass", reqLevel = 70 },
    [28192] = { name = "Helm of Desolation", source = "Aeonus", slot = "Head", type = "Mail Armor", zone = "The Black Morass", reqLevel = 70 },
    [28193] = { name = "Mana-Etched Crown", source = "Aeonus", slot = "Head", type = "Cloth Armor", zone = "The Black Morass", reqLevel = 70 },
    [28194] = { name = "Primal Surge Bracers", source = "Aeonus", slot = "Wrist", type = "Mail Armor", zone = "The Black Morass", reqLevel = 70 },
    [28206] = { name = "Cowl of the Guiltless", source = "Aeonus", slot = "Head", type = "Leather Armor", zone = "The Black Morass", reqLevel = 70 },
    [28207] = { name = "Pauldrons of the Crimson Flight", source = "Aeonus", slot = "Shoulder", type = "Plate Armor", zone = "The Black Morass", reqLevel = 70 }
}

SGJ.DungeonDB["Mechanar"] = {
    [22920] = { name = "Mana Wrath", source = "Pathaleon the Calculator", slot = "Main Hand", type = "One-Handed Sword", zone = "The Mechanar", reqLevel = 70 },
    [27899] = { name = "Moonglade Robe", source = "Pathaleon the Calculator", slot = "Chest", type = "Leather Armor", zone = "The Mechanar", reqLevel = 70 },
    [28202] = { name = "Tunic of Assassination", source = "Pathaleon the Calculator", slot = "Chest", type = "Leather Armor", zone = "The Mechanar", reqLevel = 70 },
    [28204] = { name = "Totem of the Void", source = "Zone Drop", slot = "Relic", type = "Totem", zone = "The Mechanar", reqLevel = 70 },
    [28248] = { name = "Capacitus' Cloak of Calibration", source = "Zone Drop", slot = "Back", type = "Cloak", zone = "The Mechanar", reqLevel = 70 },
    [28249] = { name = "Vestia's Pauldrons of Inner Grace", source = "Zone Drop", slot = "Shoulder", type = "Cloth Armor", zone = "The Mechanar", reqLevel = 70 },
    [28250] = { name = "Boots of the Glade-Keeper", source = "Zone Drop", slot = "Feet", type = "Leather Armor", zone = "The Mechanar", reqLevel = 70 },
    [28251] = { name = "Bloodfyre Robes of Annihilation", source = "Zone Drop", slot = "Chest", type = "Cloth Armor", zone = "The Mechanar", reqLevel = 70 },
    [28252] = { name = "Plasma Rat's Hyper-Scythe", source = "Mechano-Lord Capacitus", slot = "Two-Hand", type = "Polearm", zone = "The Mechanar", reqLevel = 70 },
    [28253] = { name = "Warp Engineer's Prismatic Chain", source = "Mechano-Lord Capacitus", slot = "Neck", type = "Amulet", zone = "The Mechanar", reqLevel = 70 },
    [28254] = { name = "Lunar-Claw Pauldrons", source = "Mechano-Lord Capacitus", slot = "Shoulder", type = "Leather Armor", zone = "The Mechanar", reqLevel = 70 },
    [28255] = { name = "Thoriumweave Cloak", source = "Mechano-Lord Capacitus", slot = "Back", type = "Cloak", zone = "The Mechanar", reqLevel = 70 },
    [28256] = { name = "Hammer of the Penitent", source = "Mechano-Lord Capacitus", slot = "Main Hand", type = "One-Handed Mace", zone = "The Mechanar", reqLevel = 70 },
    [28257] = { name = "Nethershrike", source = "Nethermancer Sepethrea", slot = "Thrown", type = "Thrown Weapon", zone = "The Mechanar", reqLevel = 70 },
    [28258] = { name = "Cosmic Lifeband", source = "Nethermancer Sepethrea", slot = "Finger", type = "Ring", zone = "The Mechanar", reqLevel = 70 },
    [28259] = { name = "Manual of the Nethermancer", source = "Nethermancer Sepethrea", slot = "Held In Off-hand", type = "Off-hand Frill", zone = "The Mechanar", reqLevel = 70 },
    [28260] = { name = "Jade-Skull Breastplate", source = "Nethermancer Sepethrea", slot = "Chest", type = "Plate Armor", zone = "The Mechanar", reqLevel = 70 },
    [28262] = { name = "Stellaris", source = "Nethermancer Sepethrea", slot = "One-Hand", type = "One-Handed Axe", zone = "The Mechanar", reqLevel = 70 },
    [28263] = { name = "Dath'Remar's Ring of Defense", source = "Pathaleon the Calculator", slot = "Finger", type = "Ring", zone = "The Mechanar", reqLevel = 70 },
    [28265] = { name = "Molten Earth Kilt", source = "Pathaleon the Calculator", slot = "Legs", type = "Mail Armor", zone = "The Mechanar", reqLevel = 70 },
    [28266] = { name = "Edge of the Cosmos", source = "Pathaleon the Calculator", slot = "One-Hand", type = "One-Handed Sword", zone = "The Mechanar", reqLevel = 70 },
    [28267] = { name = "Baba's Cloak of Arcanistry", source = "Pathaleon the Calculator", slot = "Back", type = "Cloak", zone = "The Mechanar", reqLevel = 70 },
    [28269] = { name = "Beast Lord Helm", source = "Pathaleon the Calculator", slot = "Head", type = "Mail Armor", zone = "The Mechanar", reqLevel = 70 },
    [28275] = { name = "Incanter's Cowl", source = "Pathaleon the Calculator", slot = "Head", type = "Cloth Armor", zone = "The Mechanar", reqLevel = 70 },
    [28278] = { name = "Helm of the Righteous", source = "Pathaleon the Calculator", slot = "Head", type = "Plate Armor", zone = "The Mechanar", reqLevel = 70 },
    [28285] = { name = "Telescopic Sharprifle", source = "Pathaleon the Calculator", slot = "Ranged", type = "Gun", zone = "The Mechanar", reqLevel = 70 },
    [28288] = { name = "Abacus of Violent Odds", source = "Pathaleon the Calculator", slot = "Trinket", type = "Trinket", zone = "The Mechanar", reqLevel = 70 }
}

SGJ.DungeonDB["MagistersTerrace"] = {
    [34470] = { name = "Timbal's Focusing Crystal", source = "Priestess Delrissa", slot = "Trinket", type = "Trinket", zone = "Magisters' Terrace", reqLevel = 70 },
    [34471] = { name = "Vial of the Sunwell", source = "Priestess Delrissa", slot = "Trinket", type = "Trinket", zone = "Magisters' Terrace", reqLevel = 70 },
    [34472] = { name = "Shard of Contempt", source = "Priestess Delrissa", slot = "Trinket", type = "Trinket", zone = "Magisters' Terrace", reqLevel = 70 },
    [34473] = { name = "Commendation of Kael'thas", source = "Priestess Delrissa", slot = "Trinket", type = "Trinket", zone = "Magisters' Terrace", reqLevel = 70 },
    [34601] = { name = "Shoulderplates of Everlasting Pain", source = "Selin Fireheart", slot = "Shoulder", type = "Plate Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34602] = { name = "Eversong Cuffs", source = "Selin Fireheart", slot = "Wrist", type = "Leather Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34603] = { name = "Distracting Blades", source = "Selin Fireheart", slot = "Thrown", type = "Thrown Weapon", zone = "Magisters' Terrace", reqLevel = 70 },
    [34604] = { name = "Jaded Crystal Dagger", source = "Selin Fireheart", slot = "Main Hand", type = "Dagger", zone = "Magisters' Terrace", reqLevel = 70 },
    [34605] = { name = "Breastplate of Fierce Survival", source = "Vexallus", slot = "Chest", type = "Plate Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34606] = { name = "Edge of Oppression", source = "Vexallus", slot = "One-Hand", type = "Dagger", zone = "Magisters' Terrace", reqLevel = 70 },
    [34607] = { name = "Fel-tinged Mantle", source = "Vexallus", slot = "Shoulder", type = "Cloth Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34608] = { name = "Rod of the Blazing Light", source = "Vexallus", slot = "Two-Hand", type = "Staff", zone = "Magisters' Terrace", reqLevel = 70 },
    [34609] = { name = "Quickening Blade of the Prince", source = "Kael'thas Sunstrider", slot = "One-Hand", type = "One-Handed Sword", zone = "Magisters' Terrace", reqLevel = 70 },
    [34610] = { name = "Scarlet Sin'dorei Robes", source = "Kael'thas Sunstrider", slot = "Chest", type = "Cloth Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34611] = { name = "Cudgel of Consecration", source = "Kael'thas Sunstrider", slot = "Main Hand", type = "One-Handed Mace", zone = "Magisters' Terrace", reqLevel = 70 },
    [34612] = { name = "Greaves of the Penitent Knight", source = "Kael'thas Sunstrider", slot = "Feet", type = "Plate Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34613] = { name = "Shoulderpads of the Silvermoon Retainer", source = "Kael'thas Sunstrider", slot = "Shoulder", type = "Leather Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34614] = { name = "Tunic of the Ranger Lord", source = "Kael'thas Sunstrider", slot = "Chest", type = "Mail Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34615] = { name = "Netherforce Chestplate", source = "Kael'thas Sunstrider", slot = "Chest", type = "Plate Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34616] = { name = "Breeching Comet", source = "Kael'thas Sunstrider", slot = "One-Hand", type = "One-Handed Axe", zone = "Magisters' Terrace", reqLevel = 70 },
    [35275] = { name = "Orb of the Sin'dorei", source = "Boss Drop", slot = "Held In Off-hand", type = "Off-hand Frill", zone = "Magisters' Terrace", reqLevel = 70 },
    [34625] = { name = "Kharmaa's Ring of Fate", source = "Kael'thas Sunstrider", slot = "Finger", type = "Ring", zone = "Magisters' Terrace", reqLevel = 70 },
    [34697] = { name = "Bindings of Raging Fire", source = "Selin Fireheart", slot = "Wrist", type = "Cloth Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34698] = { name = "Bracers of the Forest Stalker", source = "Selin Fireheart", slot = "Wrist", type = "Mail Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34699] = { name = "Sun-forged Cleaver", source = "Selin Fireheart", slot = "One-Hand", type = "One-Handed Axe", zone = "Magisters' Terrace", reqLevel = 70 },
    [34700] = { name = "Gauntlets of Divine Blessings", source = "Selin Fireheart", slot = "Hands", type = "Plate Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34701] = { name = "Leggings of the Betrayed", source = "Selin Fireheart", slot = "Legs", type = "Leather Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34702] = { name = "Cloak of Swift Mending", source = "Selin Fireheart", slot = "Back", type = "Cloak", zone = "Magisters' Terrace", reqLevel = 70 },
    [34703] = { name = "Latro's Dancing Blade", source = "Vexallus", slot = "One-Hand", type = "One-Handed Sword", zone = "Magisters' Terrace", reqLevel = 70 },
    [34704] = { name = "Band of Arcane Alacrity", source = "Vexallus", slot = "Finger", type = "Ring", zone = "Magisters' Terrace", reqLevel = 70 },
    [34705] = { name = "Bracers of Divine Infusion", source = "Vexallus", slot = "Wrist", type = "Cloth Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34706] = { name = "Band of Determination", source = "Vexallus", slot = "Finger", type = "Ring", zone = "Magisters' Terrace", reqLevel = 70 },
    [34707] = { name = "Boots of Resuscitation", source = "Vexallus", slot = "Feet", type = "Leather Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34708] = { name = "Cloak of the Coming Night", source = "Vexallus", slot = "Back", type = "Cloak", zone = "Magisters' Terrace", reqLevel = 70 },
    [34783] = { name = "Nightstrike", source = "Priestess Delrissa", slot = "Thrown", type = "Thrown Weapon", zone = "Magisters' Terrace", reqLevel = 70 },
    [34788] = { name = "Duskhallow Mantle", source = "Priestess Delrissa", slot = "Shoulder", type = "Cloth Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34789] = { name = "Bracers of Slaughter", source = "Priestess Delrissa", slot = "Wrist", type = "Plate Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34790] = { name = "Battle-mace of the High Priestess", source = "Priestess Delrissa", slot = "Main Hand", type = "One-Handed Mace", zone = "Magisters' Terrace", reqLevel = 70 },
    [34791] = { name = "Gauntlets of the Tranquil Waves", source = "Priestess Delrissa", slot = "Hands", type = "Mail Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34792] = { name = "Cloak of the Betrayed", source = "Priestess Delrissa", slot = "Back", type = "Cloak", zone = "Magisters' Terrace", reqLevel = 70 },
    [34793] = { name = "Cord of Reconstruction", source = "Kael'thas Sunstrider", slot = "Waist", type = "Cloth Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34794] = { name = "Axe of Shattered Dreams", source = "Kael'thas Sunstrider", slot = "Two-Hand", type = "Two-Handed Axe", zone = "Magisters' Terrace", reqLevel = 70 },
    [34795] = { name = "Helm of Sanctification", source = "Kael'thas Sunstrider", slot = "Head", type = "Plate Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34796] = { name = "Robes of Summer Flame", source = "Kael'thas Sunstrider", slot = "Chest", type = "Leather Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34797] = { name = "Sun-infused Focus Staff", source = "Kael'thas Sunstrider", slot = "Two-Hand", type = "Staff", zone = "Magisters' Terrace", reqLevel = 70 },
    [34798] = { name = "Band of Celerity", source = "Kael'thas Sunstrider", slot = "Finger", type = "Ring", zone = "Magisters' Terrace", reqLevel = 70 },
    [34799] = { name = "Hauberk of the War Bringer", source = "Kael'thas Sunstrider", slot = "Chest", type = "Mail Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34807] = { name = "Sunstrider Warboots", source = "Kael'thas Sunstrider", slot = "Feet", type = "Plate Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34808] = { name = "Gloves of Arcane Acuity", source = "Kael'thas Sunstrider", slot = "Hands", type = "Cloth Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34809] = { name = "Sunrage Treads", source = "Kael'thas Sunstrider", slot = "Feet", type = "Leather Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34810] = { name = "Cloak of Blade Turning", source = "Kael'thas Sunstrider", slot = "Back", type = "Cloak", zone = "Magisters' Terrace", reqLevel = 70 }
}

SGJ.DungeonDB["ShadowLabyrinth"] = {
    [24309] = { name = "Moonglade Handwraps", source = "Blackheart the Inciter", slot = "Hands", type = "Leather Armor", zone = "Shadow Labyrinth", reqLevel = 70 },
    [27468] = { name = "Hallowed Pauldrons", source = "Grandmaster Vorpil", slot = "Shoulder", type = "Cloth Armor", zone = "Shadow Labyrinth", reqLevel = 70 },
    [27775] = { name = "Spaulders of Oblivion", source = "Murmur", slot = "Shoulder", type = "Cloth Armor", zone = "Shadow Labyrinth", reqLevel = 70 },
    [27778] = { name = "Shoulderguards of the Bold", source = "Murmur", slot = "Shoulder", type = "Plate Armor", zone = "Shadow Labyrinth", reqLevel = 70 },
    [27884] = { name = "Ornate Boots of the Sanctified", source = "Ambassador Hellmaw", slot = "Feet", type = "Plate Armor", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27885] = { name = "Soul-Wand of the Aldor", source = "Ambassador Hellmaw", slot = "Ranged", type = "Wand", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27886] = { name = "Idol of the Emerald Queen", source = "Ambassador Hellmaw", slot = "Relic", type = "Idol", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27887] = { name = "Platinum Shield of the Valorous", source = "Ambassador Hellmaw", slot = "Shield", type = "Shield", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27888] = { name = "Dream-Wing Helm", source = "Ambassador Hellmaw", slot = "Head", type = "Mail Armor", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27889] = { name = "Jaedenfire Gloves of Annihilation", source = "Ambassador Hellmaw", slot = "Hands", type = "Cloth Armor", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27890] = { name = "Wand of the Netherwing", source = "Blackheart the Inciter", slot = "Ranged", type = "Wand", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27891] = { name = "Adamantine Figurine", source = "Blackheart the Inciter", slot = "Trinket", type = "Trinket", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27892] = { name = "Cloak of the Inciter", source = "Blackheart the Inciter", slot = "Back", type = "Cloak", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27893] = { name = "Ornate Leggings of the Venerated", source = "Blackheart the Inciter", slot = "Legs", type = "Plate Armor", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27897] = { name = "Breastplate of Many Graces", source = "Grandmaster Vorpil", slot = "Chest", type = "Plate Armor", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27898] = { name = "Wrathfire Hand-Cannon", source = "Grandmaster Vorpil", slot = "Ranged", type = "Gun", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27900] = { name = "Jewel of Charismatic Mystique", source = "Grandmaster Vorpil", slot = "Trinket", type = "Trinket", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27901] = { name = "Blackout Truncheon", source = "Grandmaster Vorpil", slot = "One-Hand", type = "One-Handed Mace", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27902] = { name = "Silent Slippers of Meditation", source = "Murmur", slot = "Feet", type = "Cloth Armor", zone = "Shadow Labyrinth", reqLevel = 70 },
    [27903] = { name = "Sonic Spear", source = "Murmur", slot = "Two-Hand", type = "Polearm", zone = "Shadow Labyrinth", reqLevel = 70 },
    [27905] = { name = "Greatsword of Horrid Dreams", source = "Murmur", slot = "Main Hand", type = "One-Handed Sword", zone = "Shadow Labyrinth", reqLevel = 70 },
    [27908] = { name = "Leggings of Assassination", source = "Murmur", slot = "Legs", type = "Leather Armor", zone = "Shadow Labyrinth", reqLevel = 70 },
    [27909] = { name = "Tidefury Kilt", source = "Murmur", slot = "Legs", type = "Mail Armor", zone = "Shadow Labyrinth", reqLevel = 70 },
    [27910] = { name = "Silvermoon Crest Shield", source = "Murmur", slot = "Shield", type = "Shield", zone = "Shadow Labyrinth", reqLevel = 70 },
    [27912] = { name = "Harness of the Deep Currents", source = "Murmur", slot = "Chest", type = "Mail Armor", zone = "Shadow Labyrinth", reqLevel = 70 },
    [27913] = { name = "Whispering Blade of Slaying", source = "Murmur", slot = "One-Hand", type = "Dagger", zone = "Shadow Labyrinth", reqLevel = 70 },
    [28134] = { name = "Brooch of Heightened Potential", source = "Blackheart the Inciter", slot = "Neck", type = "Amulet", zone = "Shadow Labyrinth", reqLevel = 68 },
    [28230] = { name = "Hallowed Garments", source = "Murmur", slot = "Chest", type = "Cloth Armor", zone = "Shadow Labyrinth", reqLevel = 70 },
    [28232] = { name = "Robe of Oblivion", source = "Murmur", slot = "Chest", type = "Cloth Armor", zone = "Shadow Labyrinth", reqLevel = 70 }
}

SGJ.DungeonDB["Arcatraz"] = {
    [28205] = { name = "Breastplate of the Bold", source = "Zone Drop", slot = "Chest", type = "Plate Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28231] = { name = "Tidefury Chestpiece", source = "Zone Drop", slot = "Chest", type = "Mail Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28372] = { name = "Idol of Feral Shadows", source = "Zereketh the Unbound", slot = "Relic", type = "Idol", zone = "The Arcatraz", reqLevel = 70 },
    [28373] = { name = "Cloak of Scintillating Auras", source = "Zereketh the Unbound", slot = "Back", type = "Cloak", zone = "The Arcatraz", reqLevel = 70 },
    [28374] = { name = "Mana-Sphere Shoulderguards", source = "Zereketh the Unbound", slot = "Shoulder", type = "Cloth Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28375] = { name = "Rubium War-Girdle", source = "Zereketh the Unbound", slot = "Waist", type = "Plate Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28384] = { name = "Outland Striders", source = "Zereketh the Unbound", slot = "Feet", type = "Mail Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28386] = { name = "Nether Core's Control Rod", source = "Dalliah the Doomsayer", slot = "Ranged", type = "Wand", zone = "The Arcatraz", reqLevel = 70 },
    [28387] = { name = "Lamp of Peaceful Repose", source = "Dalliah the Doomsayer", slot = "Held In Off-hand", type = "Off-hand Frill", zone = "The Arcatraz", reqLevel = 70 },
    [28390] = { name = "Thatia's Self-Correcting Gauntlets", source = "Dalliah the Doomsayer", slot = "Hands", type = "Plate Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28391] = { name = "Worldfire Chestguard", source = "Dalliah the Doomsayer", slot = "Chest", type = "Mail Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28392] = { name = "Reflex Blades", source = "Dalliah the Doomsayer", slot = "Main Hand", type = "Fist Weapon", zone = "The Arcatraz", reqLevel = 70 },
    [28393] = { name = "Warmaul of Infused Light", source = "Wrath-Scryer Soccothrates", slot = "Two-Hand", type = "Two-Handed Mace", zone = "The Arcatraz", reqLevel = 70 },
    [28394] = { name = "Ryngo's Band of Ingenuity", source = "Wrath-Scryer Soccothrates", slot = "Finger", type = "Ring", zone = "The Arcatraz", reqLevel = 70 },
    [28396] = { name = "Gloves of the Unbound", source = "Wrath-Scryer Soccothrates", slot = "Hands", type = "Leather Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28397] = { name = "Emberhawk Crossbow", source = "Wrath-Scryer Soccothrates", slot = "Ranged", type = "Crossbow", zone = "The Arcatraz", reqLevel = 70 },
    [28398] = { name = "The Sleeper's Cord", source = "Wrath-Scryer Soccothrates", slot = "Waist", type = "Leather Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28403] = { name = "Doomplate Chestguard", source = "Zone Drop", slot = "Chest", type = "Plate Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28406] = { name = "Sigil-Laced Boots", source = "Zone Drop", slot = "Feet", type = "Cloth Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28407] = { name = "Elementium Band of the Sentry", source = "Zone Drop", slot = "Finger", type = "Ring", zone = "The Arcatraz", reqLevel = 70 },
    [28412] = { name = "Lamp of Peaceful Radiance", source = "Zone Drop", slot = "Held In Off-hand", type = "Off-hand Frill", zone = "The Arcatraz", reqLevel = 70 },
    [28413] = { name = "Hallowed Crown", source = "Zone Drop", slot = "Head", type = "Cloth Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28414] = { name = "Helm of Assassination", source = "Zone Drop", slot = "Head", type = "Leather Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28415] = { name = "Hood of Oblivion", source = "Zone Drop", slot = "Head", type = "Cloth Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28416] = { name = "Hungering Spineripper", source = "Zone Drop", slot = "One-Hand", type = "Dagger", zone = "The Arcatraz", reqLevel = 70 },
    [28418] = { name = "Shiffar's Nexus-Horn", source = "Zone Drop", slot = "Trinket", type = "Trinket", zone = "The Arcatraz", reqLevel = 70 },
    [28419] = { name = "Choker of Fluid Thought", source = "Zone Drop", slot = "Neck", type = "Amulet", zone = "The Arcatraz", reqLevel = 70 },
    [29241] = { name = "Belt of Depravity", source = "Zone Drop", slot = "Waist", type = "Cloth Armor", zone = "The Arcatraz", reqLevel = 70 },
    [29248] = { name = "Shadowstep Striders", source = "Zone Drop", slot = "Feet", type = "Leather Armor", zone = "The Arcatraz", reqLevel = 70 },
    [29252] = { name = "Bracers of Dignity", source = "Zone Drop", slot = "Wrist", type = "Plate Armor", zone = "The Arcatraz", reqLevel = 70 },
    [29360] = { name = "Vileblade of the Betrayer", source = "Zone Drop", slot = "One-Hand", type = "Dagger", zone = "The Arcatraz", reqLevel = 70 }
}

SGJ.DungeonDB["Botanica"] = {
    [27739] = { name = "Spaulders of the Righteous", source = "Laj", slot = "Shoulder", type = "Plate Armor", zone = "The Botanica", reqLevel = 70 },
    [28228] = { name = "Beast Lord Cuirass", source = "Warp Splinter", slot = "Chest", type = "Mail Armor", zone = "The Botanica", reqLevel = 70 },
    [28229] = { name = "Incanter's Robe", source = "Warp Splinter", slot = "Chest", type = "Cloth Armor", zone = "The Botanica", reqLevel = 70 },
    [28296] = { name = "Libram of the Lightbringer", source = "Commander Sarannis", slot = "Relic", type = "Libram", zone = "The Botanica", reqLevel = 70 },
    [28301] = { name = "Syrannis' Mystic Sheen", source = "Commander Sarannis", slot = "Back", type = "Cloak", zone = "The Botanica", reqLevel = 70 },
    [28304] = { name = "Prismatic Mittens of Mending", source = "Commander Sarannis", slot = "Hands", type = "Cloth Armor", zone = "The Botanica", reqLevel = 70 },
    [28306] = { name = "Towering Mantle of the Hunt", source = "Commander Sarannis", slot = "Shoulder", type = "Mail Armor", zone = "The Botanica", reqLevel = 70 },
    [28311] = { name = "Revenger", source = "Commander Sarannis", slot = "One-Hand", type = "One-Handed Sword", zone = "The Botanica", reqLevel = 70 },
    [28315] = { name = "Stormreaver Warblades", source = "High Botanist Freywinn", slot = "Off Hand", type = "Fist Weapon", zone = "The Botanica", reqLevel = 70 },
    [28316] = { name = "Aegis of the Sunbird", source = "High Botanist Freywinn", slot = "Shield", type = "Shield", zone = "The Botanica", reqLevel = 70 },
    [28317] = { name = "Energis Armwraps", source = "High Botanist Freywinn", slot = "Hands", type = "Cloth Armor", zone = "The Botanica", reqLevel = 70 },
    [28318] = { name = "Obsidian Clodstompers", source = "High Botanist Freywinn", slot = "Feet", type = "Plate Armor", zone = "The Botanica", reqLevel = 70 },
    [28321] = { name = "Enchanted Thorium Torque", source = "High Botanist Freywinn", slot = "Neck", type = "Amulet", zone = "The Botanica", reqLevel = 70 },
    [28322] = { name = "Runed Dagger of Solace", source = "Thorngrin the Tender", slot = "Main Hand", type = "Dagger", zone = "The Botanica", reqLevel = 70 },
    [28323] = { name = "Ring of Umbral Doom", source = "Thorngrin the Tender", slot = "Finger", type = "Ring", zone = "The Botanica", reqLevel = 70 },
    [28324] = { name = "Gauntlets of Cruel Intention", source = "Thorngrin the Tender", slot = "Hands", type = "Plate Armor", zone = "The Botanica", reqLevel = 70 },
    [28325] = { name = "Dreamer's Dragonstaff", source = "Thorngrin the Tender", slot = "Two-Hand", type = "Staff", zone = "The Botanica", reqLevel = 70 },
    [28327] = { name = "Arcane Netherband", source = "Thorngrin the Tender", slot = "Finger", type = "Ring", zone = "The Botanica", reqLevel = 70 },
    [28328] = { name = "Mithril-Bark Cloak", source = "Laj", slot = "Back", type = "Cloak", zone = "The Botanica", reqLevel = 70 },
    [28338] = { name = "Devil-Stitched Leggings", source = "Laj", slot = "Legs", type = "Cloth Armor", zone = "The Botanica", reqLevel = 70 },
    [28339] = { name = "Boots of the Shifting Sands", source = "Laj", slot = "Feet", type = "Leather Armor", zone = "The Botanica", reqLevel = 70 },
    [28340] = { name = "Mantle of Autumn", source = "Laj", slot = "Shoulder", type = "Leather Armor", zone = "The Botanica", reqLevel = 70 },
    [28341] = { name = "Warpstaff of Arcanum", source = "Warp Splinter", slot = "Two-Hand", type = "Staff", zone = "The Botanica", reqLevel = 70 },
    [28342] = { name = "Warp Infused Drape", source = "Warp Splinter", slot = "Chest", type = "Cloth Armor", zone = "The Botanica", reqLevel = 70 },
    [28343] = { name = "Jagged Bark Pendant", source = "Warp Splinter", slot = "Neck", type = "Amulet", zone = "The Botanica", reqLevel = 70 },
    [28345] = { name = "Warp Splinter's Thorn", source = "Warp Splinter", slot = "One-Hand", type = "Dagger", zone = "The Botanica", reqLevel = 70 },
    [28347] = { name = "Warpscale Leggings", source = "Warp Splinter", slot = "Legs", type = "Leather Armor", zone = "The Botanica", reqLevel = 70 },
    [28348] = { name = "Moonglade Cowl", source = "Warp Splinter", slot = "Head", type = "Leather Armor", zone = "The Botanica", reqLevel = 70 },
    [28349] = { name = "Tidefury Helm", source = "Warp Splinter", slot = "Head", type = "Mail Armor", zone = "The Botanica", reqLevel = 70 },
    [28350] = { name = "Warhelm of the Bold", source = "Warp Splinter", slot = "Head", type = "Plate Armor", zone = "The Botanica", reqLevel = 70 },
    [28367] = { name = "Greatsword of Forlorn Visions", source = "Warp Splinter", slot = "Two-Hand", type = "Two-Handed Sword", zone = "The Botanica", reqLevel = 70 },
    [28370] = { name = "Bangle of Endless Blessings", source = "Warp Splinter", slot = "Trinket", type = "Trinket", zone = "The Botanica", reqLevel = 70 },
    [28371] = { name = "Netherfury Cape", source = "Warp Splinter", slot = "Back", type = "Cloak", zone = "The Botanica", reqLevel = 70 }
}

SGJ.DungeonDB["Steamvault"] = {
    [27475] = { name = "Gauntlets of the Bold", source = "Warlord Kalithresh", slot = "Hands", type = "Plate Armor", zone = "The Steamvault", reqLevel = 70 },
    [27508] = { name = "Incanter's Gloves", source = "Hydromancer Thespia", slot = "Hands", type = "Cloth Armor", zone = "The Steamvault", reqLevel = 70 },
    [27510] = { name = "Tidefury Gauntlets", source = "Warlord Kalithresh", slot = "Hands", type = "Mail Armor", zone = "The Steamvault", reqLevel = 70 },
    [27737] = { name = "Moonglade Shoulders", source = "Warlord Kalithresh", slot = "Shoulder", type = "Leather Armor", zone = "The Steamvault", reqLevel = 70 },
    [27738] = { name = "Incanter's Pauldrons", source = "Warlord Kalithresh", slot = "Shoulder", type = "Cloth Armor", zone = "The Steamvault", reqLevel = 70 },
    [27783] = { name = "Moonrage Girdle", source = "Hydromancer Thespia", slot = "Waist", type = "Leather Armor", zone = "The Steamvault", reqLevel = 68 },
    [27784] = { name = "Scintillating Coral Band", source = "Hydromancer Thespia", slot = "Finger", type = "Ring", zone = "The Steamvault", reqLevel = 68 },
    [27787] = { name = "Chestguard of No Remorse", source = "Hydromancer Thespia", slot = "Chest", type = "Leather Armor", zone = "The Steamvault", reqLevel = 68 },
    [27789] = { name = "Cloak of Whispering Shells", source = "Hydromancer Thespia", slot = "Back", type = "Cloak", zone = "The Steamvault", reqLevel = 68 },
    [27790] = { name = "Mask of Penance", source = "Mekgineer Steamrigger", slot = "Head", type = "Plate Armor", zone = "The Steamvault", reqLevel = 68 },
    [27791] = { name = "Serpentcrest Life-Staff", source = "Mekgineer Steamrigger", slot = "Two-Hand", type = "Staff", zone = "The Steamvault", reqLevel = 68 },
    [27792] = { name = "Steam-Hinge Chain of Valor", source = "Mekgineer Steamrigger", slot = "Neck", type = "Amulet", zone = "The Steamvault", reqLevel = 68 },
    [27793] = { name = "Earth Mantle Handwraps", source = "Mekgineer Steamrigger", slot = "Hands", type = "Mail Armor", zone = "The Steamvault", reqLevel = 68 },
    [27794] = { name = "Recoilless Rocket Ripper X-54", source = "Mekgineer Steamrigger", slot = "Ranged", type = "Gun", zone = "The Steamvault", reqLevel = 68 },
    [27795] = { name = "Sash of Serpentra", source = "Warlord Kalithresh", slot = "Waist", type = "Cloth Armor", zone = "The Steamvault", reqLevel = 70 },
    [27799] = { name = "Vermillion Robes of the Dominant", source = "Warlord Kalithresh", slot = "Chest", type = "Cloth Armor", zone = "The Steamvault", reqLevel = 70 },
    [27801] = { name = "Beast Lord Mantle", source = "Warlord Kalithresh", slot = "Shoulder", type = "Mail Armor", zone = "The Steamvault", reqLevel = 70 },
    [27804] = { name = "Devilshark Cape", source = "Warlord Kalithresh", slot = "Back", type = "Cloak", zone = "The Steamvault", reqLevel = 70 },
    [27805] = { name = "Ring of the Silver Hand", source = "Warlord Kalithresh", slot = "Finger", type = "Ring", zone = "The Steamvault", reqLevel = 70 },
    [27806] = { name = "Fathomheart Gauntlets", source = "Warlord Kalithresh", slot = "Hands", type = "Mail Armor", zone = "The Steamvault", reqLevel = 70 },
    [28203] = { name = "Beast Lord Leggings", source = "Warlord Kalithresh", slot = "Legs", type = "Mail Armor", zone = "The Steamvault", reqLevel = 70 },
    [27874] = { name = "Breastplate of the Righteous", source = "Warlord Kalithresh", slot = "Chest", type = "Plate Armor", zone = "The Steamvault", reqLevel = 70 }
}