local addonName, SGJ = ...

-- 2. INITIALIZE DB
SGJ.DungeonDB = SGJ.DungeonDB or {}

-- ============================================================
-- TBC HEROICS DUNGEONS
-- ============================================================

SGJ.DungeonDB["Ramparts_HC"] = {
    [24044] = { name = "Shadowrend Longblade", source = "Watchkeeper Gargolmar", slot = "Main Hand", type = "One-Handed Sword", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24021] = { name = "Light-Touched Breastplate", source = "Watchkeeper Gargolmar", slot = "Chest", type = "Plate Armor", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24022] = { name = "Scale Leggings of the Skirmisher", source = "Watchkeeper Gargolmar", slot = "Legs", type = "Mail Armor", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24023] = { name = "Bracers of Finesse", source = "Watchkeeper Gargolmar", slot = "Wrist", type = "Leather Armor", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24024] = { name = "Pauldrons of Arcane Rage", source = "Watchkeeper Gargolmar", slot = "Shoulder", type = "Cloth Armor", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24044] = { name = "Hellreaver", source = "Reinforced Fel Iron Chest", slot = "Two-Hand", type = "Polearm", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24020] = { name = "Band of Renewal", source = "Reinforced Fel Iron Chest", slot = "Finger", type = "Ring", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24046] = { name = "Kilt of Rolling Thunders", source = "Reinforced Fel Iron Chest", slot = "Legs", type = "Mail Armor", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24045] = { name = "Shifting Sash of Midnight", source = "Reinforced Fel Iron Chest", slot = "Waist", type = "Leather Armor", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24063] = { name = "Ironsole Clompers", source = "Reinforced Fel Iron Chest", slot = "Feet", type = "Plate Armor", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24064] = { name = "Crystalfire Staff", source = "Omor the Unscarred", slot = "Two-Hand", type = "Staff", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24069] = { name = "Garrote-String Necklace", source = "Omor the Unscarred", slot = "Neck", type = "Amulet", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24073] = { name = "Lifegiver Britches", source = "Reinforced Fel Iron Chest", slot = "Legs", type = "Cloth Armor", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24083] = { name = "Bloodstained Ravager Gauntlets", source = "Omor the Unscarred", slot = "Hands", type = "Mail Armor", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24090] = { name = "Tenacious Defender", source = "Omor the Unscarred", slot = "Waist", type = "Plate Armor", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24091] = { name = "Heart Fire Warhammer", source = "Omor the Unscarred", slot = "Two-Hand", type = "Two-Handed Mace", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24094] = { name = "Heartblood Prayer Beads", source = "Omor the Unscarred", slot = "Neck", type = "Amulet", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24096] = { name = "Mok'Nathal Wildercloak", source = "Reinforced Fel Iron Chest", slot = "Back", type = "Cloak", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24150] = { name = "Mok'Nathal Clan Ring", source = "Reinforced Fel Iron Chest", slot = "Finger", type = "Ring", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24151] = { name = "Witching Band", source = "Reinforced Fel Iron Chest", slot = "Finger", type = "Ring", zone = "Hellfire Ramparts", reqLevel = 60 },
    [24154] = { name = "Ursol's Claw", source = "Reinforced Fel Iron Chest", slot = "Two-Hand", type = "Staff", zone = "Hellfire Ramparts", reqLevel = 60 },
    [27447] = { name = "Bracers of Just Rewards", source = "Watchkeeper Gargolmar", slot = "Wrist", type = "Plate Armor", zone = "Hellfire Ramparts", reqLevel = 70 },
    [27448] = { name = "Cloak of the Everliving", source = "Watchkeeper Gargolmar", slot = "Back", type = "Cloak", zone = "Hellfire Ramparts", reqLevel = 70 },
    [27449] = { name = "Blood Knight Defender", source = "Watchkeeper Gargolmar", slot = "Shield", type = "Shield", zone = "Hellfire Ramparts", reqLevel = 70 },
    [27450] = { name = "Wild Stalker Boots", source = "Watchkeeper Gargolmar", slot = "Feet", type = "Mail Armor", zone = "Hellfire Ramparts", reqLevel = 70 },
    [27451] = { name = "Boots of the Darkwalker", source = "Watchkeeper Gargolmar", slot = "Feet", type = "Cloth Armor", zone = "Hellfire Ramparts", reqLevel = 70 },
    [27452] = { name = "Light Scribe Bands", source = "Zone Drop", slot = "Wrist", type = "Cloth Armor", zone = "Hellfire Ramparts", reqLevel = 70 },
    [27453] = { name = "Averinn's Ring of Slaying", source = "Zone Drop", slot = "Finger", type = "Ring", zone = "Hellfire Ramparts", reqLevel = 70 },
    [27454] = { name = "Volcanic Pauldrons", source = "Zone Drop", slot = "Shoulder", type = "Mail Armor", zone = "Hellfire Ramparts", reqLevel = 70 },
    [27455] = { name = "Irondrake Faceguard", source = "Zone Drop", slot = "Head", type = "Plate Armor", zone = "Hellfire Ramparts", reqLevel = 70 },
    [27456] = { name = "Raiments of Nature's Breath", source = "Zone Drop", slot = "Chest", type = "Leather Armor", zone = "Hellfire Ramparts", reqLevel = 70 },
    [27457] = { name = "Life Bearer's Gauntlets", source = "Zone Drop", slot = "Hands", type = "Plate Armor", zone = "Hellfire Ramparts", reqLevel = 70 },
    [27458] = { name = "Oceansong Kilt", source = "Zone Drop", slot = "Legs", type = "Mail Armor", zone = "Hellfire Ramparts", reqLevel = 70 },
    [27459] = { name = "Vambraces of Daring", source = "Zone Drop", slot = "Wrist", type = "Plate Armor", zone = "Hellfire Ramparts", reqLevel = 70 },
    [27460] = { name = "Reavers' Ring", source = "Zone Drop", slot = "Finger", type = "Ring", zone = "Hellfire Ramparts", reqLevel = 70 },
    [27461] = { name = "Chestguard of the Prowler", source = "Zone Drop", slot = "Chest", type = "Leather Armor", zone = "Hellfire Ramparts", reqLevel = 70 },
    [27462] = { name = "Crimson Bracers of Gloom", source = "Omor the Unscarred", slot = "Wrist", type = "Cloth Armor", zone = "Hellfire Ramparts", reqLevel = 70 },
    [27463] = { name = "Terror Flame Dagger", source = "Omor the Unscarred", slot = "One-Hand", type = "Dagger", zone = "Hellfire Ramparts", reqLevel = 70 },
    [27464] = { name = "Omor's Unyielding Will", source = "Omor the Unscarred", slot = "Neck", type = "Amulet", zone = "Hellfire Ramparts", reqLevel = 70 },
    [27465] = { name = "Mana-Etched Gloves", source = "Omor the Unscarred", slot = "Hands", type = "Cloth Armor", zone = "Hellfire Ramparts", reqLevel = 70 },
    [27466] = { name = "Headdress of Alacrity", source = "Omor the Unscarred", slot = "Head", type = "Cloth Armor", zone = "Hellfire Ramparts", reqLevel = 70 },
    [27467] = { name = "Silent-Strider Kneeboots", source = "Omor the Unscarred", slot = "Feet", type = "Leather Armor", zone = "Hellfire Ramparts", reqLevel = 70 },
    [27476] = { name = "Truncheon of Five Hells", source = "Omor the Unscarred", slot = "One-Hand", type = "One-Handed Mace", zone = "Hellfire Ramparts", reqLevel = 70 },
    [27477] = { name = "Faol's Signet of Cleansing", source = "Omor the Unscarred", slot = "Held In Off-hand", type = "Off-hand Frill", zone = "Hellfire Ramparts", reqLevel = 70 },
    [27478] = { name = "Girdle of the Blasted Reaches", source = "Omor the Unscarred", slot = "Waist", type = "Mail Armor", zone = "Hellfire Ramparts", reqLevel = 70 },
    [27539] = { name = "Justice Bearer's Pauldrons", source = "Omor the Unscarred", slot = "Shoulder", type = "Plate Armor", zone = "Hellfire Ramparts", reqLevel = 70 },
    [27895] = { name = "Band of Many Prisms", source = "Omor the Unscarred", slot = "Finger", type = "Ring", zone = "Hellfire Ramparts", reqLevel = 68 },
    [27906] = { name = "Crimsonforge Breastplate", source = "Omor the Unscarred", slot = "Chest", type = "Plate Armor", zone = "Hellfire Ramparts", reqLevel = 70 },
    [29238] = { name = "Lion's Heart Girdle", source = "Zone Drop", slot = "Waist", type = "Plate Armor", zone = "Hellfire Ramparts", reqLevel = 70 },
    [29264] = { name = "Tree-Mender's Belt", source = "Zone Drop", slot = "Waist", type = "Leather Armor", zone = "Hellfire Ramparts", reqLevel = 70 },
    [29346] = { name = "Feltooth Eviscerator", source = "Zone Drop", slot = "One-Hand", type = "Dagger", zone = "Hellfire Ramparts", reqLevel = 70 },
    [32077] = { name = "Wrath Infused Gauntlets", source = "Zone Drop", slot = "Hands", type = "Mail Armor", zone = "Hellfire Ramparts", reqLevel = 70 }
}
SGJ.DungeonDB["BloodFurnace_HC"] = {
    [24384] = { name = "Diamond-Core Sledgemace", source = "The Maker", slot = "Main Hand", type = "One-Handed Mace", zone = "The Blood Furnace", reqLevel = 61 },
    [24385] = { name = "Pendant of Battle-Lust", source = "The Maker", slot = "Neck", type = "Amulet", zone = "The Blood Furnace", reqLevel = 61 },
    [24386] = { name = "Libram of Saints Departed", source = "The Maker", slot = "Relic", type = "Libram", zone = "The Blood Furnace", reqLevel = 61 },
    [24387] = { name = "Ironblade Gauntlets", source = "The Maker", slot = "Hands", type = "Plate Armor", zone = "The Blood Furnace", reqLevel = 61 },
    [24388] = { name = "Girdle of the Gale Storm", source = "The Maker", slot = "Waist", type = "Mail Armor", zone = "The Blood Furnace", reqLevel = 61 },
    [24389] = { name = "Legion Blunderbuss", source = "Broggok", slot = "Ranged", type = "Gun", zone = "The Blood Furnace", reqLevel = 61 },
    [24390] = { name = "Auslese's Light Channeler", source = "Broggok", slot = "Trinket", type = "Trinket", zone = "The Blood Furnace", reqLevel = 61 },
    [24391] = { name = "Kilt of the Night Strider", source = "Broggok", slot = "Legs", type = "Leather Armor", zone = "The Blood Furnace", reqLevel = 61 },
    [24392] = { name = "Arcing Bracers", source = "Broggok", slot = "Wrist", type = "Cloth Armor", zone = "The Blood Furnace", reqLevel = 61 },
    [24393] = { name = "Bloody Surgeon's Mitts", source = "Broggok", slot = "Hands", type = "Cloth Armor", zone = "The Blood Furnace", reqLevel = 61 },
    [24394] = { name = "Warsong Howling Axe", source = "Keli'dan the Breaker", slot = "Two-Hand", type = "Two-Handed Axe", zone = "The Blood Furnace", reqLevel = 61 },
    [24395] = { name = "Mindfire Waistband", source = "Keli'dan the Breaker", slot = "Waist", type = "Cloth Armor", zone = "The Blood Furnace", reqLevel = 61 },
    [24396] = { name = "Vest of Vengeance", source = "Keli'dan the Breaker", slot = "Chest", type = "Leather Armor", zone = "The Blood Furnace", reqLevel = 61 },
    [24397] = { name = "Raiments of Divine Authority", source = "Keli'dan the Breaker", slot = "Chest", type = "Cloth Armor", zone = "The Blood Furnace", reqLevel = 61 },
    [24398] = { name = "Mantle of the Dusk-Dweller", source = "Keli'dan the Breaker", slot = "Shoulder", type = "Leather Armor", zone = "The Blood Furnace", reqLevel = 61 },
    [27483] = { name = "Moon-Touched Bands", source = "The Maker", slot = "Wrist", type = "Leather Armor", zone = "The Blood Furnace", reqLevel = 70 },
    [27484] = { name = "Libram of Avengement", source = "The Maker", slot = "Relic", type = "Libram", zone = "The Blood Furnace", reqLevel = 70 },
    [27485] = { name = "Embroidered Cape of Mysteries", source = "The Maker", slot = "Back", type = "Cloak", zone = "The Blood Furnace", reqLevel = 70 },
    [27487] = { name = "Bloodlord Legplates", source = "The Maker", slot = "Legs", type = "Plate Armor", zone = "The Blood Furnace", reqLevel = 70 },
    [27488] = { name = "Mage-Collar of the Firestorm", source = "The Maker", slot = "Head", type = "Cloth Armor", zone = "The Blood Furnace", reqLevel = 70 },
    [27489] = { name = "Virtue Bearer's Vambraces", source = "Broggok", slot = "Wrist", type = "Plate Armor", zone = "The Blood Furnace", reqLevel = 70 },
    [27490] = { name = "Firebrand Battleaxe", source = "Broggok", slot = "One-Hand", type = "One-Handed Axe", zone = "The Blood Furnace", reqLevel = 70 },
    [27491] = { name = "Signet of Repose", source = "Broggok", slot = "Finger", type = "Ring", zone = "The Blood Furnace", reqLevel = 70 },
    [27492] = { name = "Moonchild Leggings", source = "Broggok", slot = "Legs", type = "Leather Armor", zone = "The Blood Furnace", reqLevel = 70 },
    [27494] = { name = "Emerald Eye Bracer", source = "Keli'dan the Breaker", slot = "Wrist", type = "Mail Armor", zone = "The Blood Furnace", reqLevel = 70 },
    [27495] = { name = "Soldier's Dog Tags", source = "Keli'dan the Breaker", slot = "Neck", type = "Amulet", zone = "The Blood Furnace", reqLevel = 70 },
    [27497] = { name = "Doomplate Gauntlets", source = "Keli'dan the Breaker", slot = "Hands", type = "Plate Armor", zone = "The Blood Furnace", reqLevel = 70 },
    [27505] = { name = "Ruby Helm of the Just", source = "Keli'dan the Breaker", slot = "Head", type = "Plate Armor", zone = "The Blood Furnace", reqLevel = 70 },
    [27506] = { name = "Robe of Effervescent Light", source = "Keli'dan the Breaker", slot = "Chest", type = "Cloth Armor", zone = "The Blood Furnace", reqLevel = 70 },
    [27507] = { name = "Adamantine Repeater", source = "Keli'dan the Breaker", slot = "Ranged", type = "Crossbow", zone = "The Blood Furnace", reqLevel = 70 },
    [27512] = { name = "The Willbreaker", source = "Keli'dan the Breaker", slot = "Main Hand", type = "One-Handed Sword", zone = "The Blood Furnace", reqLevel = 70 },
    [27514] = { name = "Leggings of the Unrepentant", source = "Keli'dan the Breaker", slot = "Legs", type = "Leather Armor", zone = "The Blood Furnace", reqLevel = 70 },
    [27522] = { name = "World's End Bracers", source = "Keli'dan the Breaker", slot = "Wrist", type = "Mail Armor", zone = "The Blood Furnace", reqLevel = 70 },
    [27788] = { name = "Bloodsworn Warboots", source = "Keli'dan the Breaker", slot = "Feet", type = "Plate Armor", zone = "The Blood Furnace", reqLevel = 68 },
    [27848] = { name = "Embroidered Spellpyre Boots", source = "Broggok", slot = "Feet", type = "Cloth Armor", zone = "The Blood Furnace", reqLevel = 70 },
    [28121] = { name = "Icon of Unyielding Courage", source = "Keli'dan the Breaker", slot = "Trinket", type = "Trinket", zone = "The Blood Furnace", reqLevel = 70 },
    [28264] = { name = "Wastewalker Tunic", source = "Keli'dan the Breaker", slot = "Chest", type = "Leather Armor", zone = "The Blood Furnace", reqLevel = 70 },
    [29239] = { name = "Eaglecrest Warboots", source = "Keli'dan the Breaker", slot = "Feet", type = "Plate Armor", zone = "The Blood Furnace", reqLevel = 70 },
    [29245] = { name = "Wave-Crest Striders", source = "Keli'dan the Breaker", slot = "Feet", type = "Mail Armor", zone = "The Blood Furnace", reqLevel = 70 },
    [29347] = { name = "Talisman of the Breaker", source = "Keli'dan the Breaker", slot = "Neck", type = "Amulet", zone = "The Blood Furnace", reqLevel = 70 },
    [32080] = { name = "Mantle of Shadowy Embrace", source = "Keli'dan the Breaker", slot = "Shoulder", type = "Leather Armor", zone = "The Blood Furnace", reqLevel = 70 }
}
SGJ.DungeonDB["SlavePens_HC"] = {
    [24356] = { name = "Wastewalker Shiv", source = "Mennu the Betrayer", slot = "Main Hand", type = "Dagger", zone = "The Slave Pens", reqLevel = 62 },
    [24357] = { name = "Vest of Living Lightning", source = "Mennu the Betrayer", slot = "Chest", type = "Mail Armor", zone = "The Slave Pens", reqLevel = 62 },
    [24359] = { name = "Princely Reign Leggings", source = "Mennu the Betrayer", slot = "Legs", type = "Cloth Armor", zone = "The Slave Pens", reqLevel = 62 },
    [24360] = { name = "Tracker's Belt", source = "Mennu the Betrayer", slot = "Waist", type = "Mail Armor", zone = "The Slave Pens", reqLevel = 62 },
    [24361] = { name = "Spellfire Longsword", source = "Mennu the Betrayer", slot = "Main Hand", type = "One-Handed Sword", zone = "The Slave Pens", reqLevel = 62 },
    [24362] = { name = "Spore-Soaked Vaneer", source = "Quagmirran", slot = "Back", type = "Cloak", zone = "The Slave Pens", reqLevel = 62 },
    [24363] = { name = "Unscarred Breastplate", source = "Quagmirran", slot = "Chest", type = "Plate Armor", zone = "The Slave Pens", reqLevel = 62 },
    [24364] = { name = "Azureplate Greaves", source = "Quagmirran", slot = "Legs", type = "Plate Armor", zone = "The Slave Pens", reqLevel = 62 },
    [24365] = { name = "Deft Handguards", source = "Quagmirran", slot = "Hands", type = "Leather Armor", zone = "The Slave Pens", reqLevel = 62 },
    [24366] = { name = "Scorpid-Sting Mantle", source = "Quagmirran", slot = "Shoulder", type = "Mail Armor", zone = "The Slave Pens", reqLevel = 62 },
    [24376] = { name = "Runed Fungalcap", source = "Rokmar the Crackler", slot = "Trinket", type = "Trinket", zone = "The Slave Pens", reqLevel = 62 },
    [24378] = { name = "Coilfang Hammer of Renewal", source = "Rokmar the Crackler", slot = "Main Hand", type = "One-Handed Mace", zone = "The Slave Pens", reqLevel = 62 },
    [24379] = { name = "Bogstrok Scale Cloak", source = "Rokmar the Crackler", slot = "Back", type = "Cloak", zone = "The Slave Pens", reqLevel = 62 },
    [24380] = { name = "Calming Spore Reed", source = "Rokmar the Crackler", slot = "Ranged", type = "Wand", zone = "The Slave Pens", reqLevel = 62 },
    [24381] = { name = "Coilfang Needler", source = "Rokmar the Crackler", slot = "Ranged", type = "Crossbow", zone = "The Slave Pens", reqLevel = 62 },
    [27541] = { name = "Archery Belt of the Broken", source = "Mennu the Betrayer", slot = "Waist", type = "Mail Armor", zone = "The Slave Pens", reqLevel = 70 },
    [27542] = { name = "Cord of Belief", source = "Mennu the Betrayer", slot = "Waist", type = "Cloth Armor", zone = "The Slave Pens", reqLevel = 70 },
    [27543] = { name = "Starlight Dagger", source = "Mennu the Betrayer", slot = "Main Hand", type = "Dagger", zone = "The Slave Pens", reqLevel = 70 },
    [27544] = { name = "Totem of Spontaneous Regrowth", source = "Mennu the Betrayer", slot = "Relic", type = "Totem", zone = "The Slave Pens", reqLevel = 70 },
    [27545] = { name = "Mennu's Scaled Leggings", source = "Mennu the Betrayer", slot = "Legs", type = "Leather Armor", zone = "The Slave Pens", reqLevel = 70 },
    [27546] = { name = "Traitor's Noose", source = "Mennu the Betrayer", slot = "Neck", type = "Amulet", zone = "The Slave Pens", reqLevel = 70 },
    [27547] = { name = "Coldwhisper Cord", source = "Rokmar the Crackler", slot = "Waist", type = "Cloth Armor", zone = "The Slave Pens", reqLevel = 70 },
    [27548] = { name = "Girdle of Many Blessings", source = "Rokmar the Crackler", slot = "Waist", type = "Plate Armor", zone = "The Slave Pens", reqLevel = 70 },
    [27549] = { name = "Wavefury Boots", source = "Rokmar the Crackler", slot = "Feet", type = "Mail Armor", zone = "The Slave Pens", reqLevel = 70 },
    [27550] = { name = "Ironscale War Cloak", source = "Rokmar the Crackler", slot = "Back", type = "Cloak", zone = "The Slave Pens", reqLevel = 70 },
    [27551] = { name = "Skeletal Necklace of Battlerage", source = "Rokmar the Crackler", slot = "Neck", type = "Amulet", zone = "The Slave Pens", reqLevel = 70 },
    [27672] = { name = "Girdle of the Immovable", source = "Quagmirran", slot = "Waist", type = "Plate Armor", zone = "The Slave Pens", reqLevel = 70 },
    [27673] = { name = "Phosphorescent Blade", source = "Quagmirran", slot = "One-Hand", type = "One-Handed Sword", zone = "The Slave Pens", reqLevel = 70 },
    [27683] = { name = "Quagmirran's Eye", source = "Quagmirran", slot = "Trinket", type = "Trinket", zone = "The Slave Pens", reqLevel = 70 },
    [27712] = { name = "Shackles of Quagmirran", source = "Quagmirran", slot = "Wrist", type = "Leather Armor", zone = "The Slave Pens", reqLevel = 70 },
    [27713] = { name = "Pauldrons of Desolation", source = "Quagmirran", slot = "Shoulder", type = "Mail Armor", zone = "The Slave Pens", reqLevel = 70 },
    [27714] = { name = "Swamplight Lantern", source = "Quagmirran", slot = "Held In Off-hand", type = "Off-hand Frill", zone = "The Slave Pens", reqLevel = 70 },
    [27740] = { name = "Band of Ursol", source = "Quagmirran", slot = "Finger", type = "Ring", zone = "The Slave Pens", reqLevel = 70 },
    [27741] = { name = "Bleeding Hollow Warhammer", source = "Quagmirran", slot = "Main Hand", type = "One-Handed Mace", zone = "The Slave Pens", reqLevel = 70 },
    [27742] = { name = "Mage-Fury Girdle", source = "Quagmirran", slot = "Waist", type = "Cloth Armor", zone = "The Slave Pens", reqLevel = 70 },
    [27796] = { name = "Mana-Etched Spaulders", source = "Quagmirran", slot = "Shoulder", type = "Cloth Armor", zone = "The Slave Pens", reqLevel = 70 },
    [27800] = { name = "Earthsoul Britches", source = "Quagmirran", slot = "Legs", type = "Leather Armor", zone = "The Slave Pens", reqLevel = 70 },
    [28124] = { name = "Liar's Cord", source = "Rokmar the Crackler", slot = "Waist", type = "Leather Armor", zone = "The Slave Pens", reqLevel = 70 },
    [28337] = { name = "Breastplate of Righteous Fury", source = "Quagmirran", slot = "Chest", type = "Plate Armor", zone = "The Slave Pens", reqLevel = 70 },
    [29242] = { name = "Boots of Blasphemy", source = "Quagmirran", slot = "Feet", type = "Cloth Armor", zone = "The Slave Pens", reqLevel = 70 },
    [29349] = { name = "Adamantine Chain of the Unbroken", source = "Quagmirran", slot = "Neck", type = "Amulet", zone = "The Slave Pens", reqLevel = 70 },
    [30538] = { name = "Midnight Legguards", source = "Quagmirran", slot = "Legs", type = "Leather Armor", zone = "The Slave Pens", reqLevel = 70 },
    [32078] = { name = "Pauldrons of Wild Magic", source = "Quagmirran", slot = "Shoulder", type = "Mail Armor", zone = "The Slave Pens", reqLevel = 70 }
}
SGJ.DungeonDB["Underbog_HC"] = {
    [27743] = { name = "Girdle of Living Flame", source = "Hungarfen", slot = "Waist", type = "Mail Armor", zone = "The Underbog", reqLevel = 70 },
    [27744] = { name = "Idol of Ursoc", source = "Hungarfen", slot = "Relic", type = "Idol", zone = "The Underbog", reqLevel = 70 },
    [27745] = { name = "Hungarhide Gauntlets", source = "Hungarfen", slot = "Hands", type = "Mail Armor", zone = "The Underbog", reqLevel = 70 },
    [27746] = { name = "Arcanium Signet Bands", source = "Hungarfen", slot = "Wrist", type = "Cloth Armor", zone = "The Underbog", reqLevel = 70 },
    [27747] = { name = "Boggspine Knuckles", source = "Hungarfen", slot = "Off Hand", type = "Fist Weapon", zone = "The Underbog", reqLevel = 70 },
    [27748] = { name = "Cassock of the Loyal", source = "Hungarfen", slot = "Legs", type = "Plate Armor", zone = "The Underbog", reqLevel = 70 },
    [27755] = { name = "Girdle of Gallantry", source = "Ghaz'an", slot = "Waist", type = "Plate Armor", zone = "The Underbog", reqLevel = 70 },
    [27757] = { name = "Greatstaff of the Leviathan", source = "Ghaz'an", slot = "Two-Hand", type = "Staff", zone = "The Underbog", reqLevel = 70 },
    [27758] = { name = "Hydra-fang Necklace", source = "Ghaz'an", slot = "Neck", type = "Amulet", zone = "The Underbog", reqLevel = 70 },
    [27759] = { name = "Headdress of the Tides", source = "Ghaz'an", slot = "Head", type = "Mail Armor", zone = "The Underbog", reqLevel = 70 },
    [27760] = { name = "Dunewind Sash", source = "Ghaz'an", slot = "Waist", type = "Leather Armor", zone = "The Underbog", reqLevel = 70 },
    [27761] = { name = "Ring of the Shadow Deeps", source = "Ghaz'an", slot = "Finger", type = "Ring", zone = "The Underbog", reqLevel = 70 },
    [27768] = { name = "Oracle Belt of Timeless Mystery", source = "The Black Stalker", slot = "Waist", type = "Cloth Armor", zone = "The Underbog", reqLevel = 70 },
    [27769] = { name = "Endbringer", source = "The Black Stalker", slot = "Two-Hand", type = "Two-Handed Sword", zone = "The Underbog", reqLevel = 70 },
    [27770] = { name = "Argussian Compass", source = "The Black Stalker", slot = "Trinket", type = "Trinket", zone = "The Underbog", reqLevel = 70 },
    [27771] = { name = "Doomplate Shoulderguards", source = "The Black Stalker", slot = "Shoulder", type = "Plate Armor", zone = "The Underbog", reqLevel = 70 },
    [27772] = { name = "Stormshield of Renewal", source = "The Black Stalker", slot = "Shield", type = "Shield", zone = "The Underbog", reqLevel = 70 },
    [27773] = { name = "Barbaric Legstraps", source = "The Black Stalker", slot = "Legs", type = "Mail Armor", zone = "The Underbog", reqLevel = 70 },
    [27779] = { name = "Bone Chain Necklace", source = "The Black Stalker", slot = "Neck", type = "Amulet", zone = "The Underbog", reqLevel = 70 },
    [27780] = { name = "Ring of Fabled Hope", source = "The Black Stalker", slot = "Finger", type = "Ring", zone = "The Underbog", reqLevel = 70 },
    [27781] = { name = "Demonfang Ritual Helm", source = "The Black Stalker", slot = "Head", type = "Cloth Armor", zone = "The Underbog", reqLevel = 70 },
    [27896] = { name = "Alembic of Infernal Power", source = "The Black Stalker", slot = "Trinket", type = "Trinket", zone = "The Underbog", reqLevel = 70 },
    [27907] = { name = "Mana-Etched Pantaloons", source = "The Black Stalker", slot = "Legs", type = "Cloth Armor", zone = "The Underbog", reqLevel = 70 },
    [27938] = { name = "Savage Mask of the Lynx Lord", source = "The Black Stalker", slot = "Head", type = "Leather Armor", zone = "The Underbog", reqLevel = 70 },
    [29265] = { name = "Barkchip Boots", source = "The Black Stalker", slot = "Feet", type = "Leather Armor", zone = "The Underbog", reqLevel = 70 },
    [29350] = { name = "The Black Stalk", source = "The Black Stalker", slot = "Ranged", type = "Wand", zone = "The Underbog", reqLevel = 70 },
    [30541] = { name = "Stormsong Kilt", source = "The Black Stalker", slot = "Legs", type = "Mail Armor", zone = "The Underbog", reqLevel = 70 },
    [32081] = { name = "Eye of the Stalker", source = "The Black Stalker", slot = "Finger", type = "Ring", zone = "The Underbog", reqLevel = 70 },
    [24413] = { name = "Totem of the Thunderhead", source = "Hungarfen", slot = "Relic", type = "Totem", zone = "The Underbog", reqLevel = 63 },
    [24450] = { name = "Manaspark Gloves", source = "Hungarfen", slot = "Hands", type = "Cloth Armor", zone = "The Underbog", reqLevel = 63 },
    [24451] = { name = "Lykul Bloodbands", source = "Hungarfen", slot = "Wrist", type = "Mail Armor", zone = "The Underbog", reqLevel = 63 },
    [24452] = { name = "Starlight Gauntlets", source = "Hungarfen", slot = "Hands", type = "Leather Armor", zone = "The Underbog", reqLevel = 63 },
    [24453] = { name = "Zangartooth Shortblade", source = "Swamplord Musel'ek", slot = "Main Hand", type = "Dagger", zone = "The Underbog", reqLevel = 63 },
    [24454] = { name = "Cloak of Enduring Swiftness", source = "Swamplord Musel'ek", slot = "Back", type = "Cloak", zone = "The Underbog", reqLevel = 63 },
    [24455] = { name = "Tunic of the Nightwatcher", source = "Swamplord Musel'ek", slot = "Chest", type = "Leather Armor", zone = "The Underbog", reqLevel = 63 },
    [24456] = { name = "Greaves of the Iron Guardian", source = "Swamplord Musel'ek", slot = "Legs", type = "Plate Armor", zone = "The Underbog", reqLevel = 63 },
    [24457] = { name = "Truth Bearer Shoulderguards", source = "Swamplord Musel'ek", slot = "Shoulder", type = "Plate Armor", zone = "The Underbog", reqLevel = 63 },
    [24458] = { name = "Studded Girdle of Virtue", source = "Ghaz'an", slot = "Waist", type = "Plate Armor", zone = "The Underbog", reqLevel = 63 },
    [24459] = { name = "Cloak of Healing Rays", source = "Ghaz'an", slot = "Back", type = "Cloak", zone = "The Underbog", reqLevel = 63 },
    [24460] = { name = "Talisman of Tenacity", source = "Ghaz'an", slot = "Neck", type = "Amulet", zone = "The Underbog", reqLevel = 63 },
    [24461] = { name = "Hatebringer", source = "Ghaz'an", slot = "Two-Hand", type = "Two-Handed Mace", zone = "The Underbog", reqLevel = 63 },
    [24462] = { name = "Luminous Pearls of Insight", source = "Ghaz'an", slot = "Neck", type = "Amulet", zone = "The Underbog", reqLevel = 63 },
    [24463] = { name = "Pauldrons of Brute Force", source = "The Black Stalker", slot = "Shoulder", type = "Plate Armor", zone = "The Underbog", reqLevel = 63 },
    [24464] = { name = "The Stalker's Fangs", source = "The Black Stalker", slot = "One-Hand", type = "Dagger", zone = "The Underbog", reqLevel = 63 },
    [24465] = { name = "Shamblehide Chestguard", source = "The Black Stalker", slot = "Chest", type = "Mail Armor", zone = "The Underbog", reqLevel = 63 },
    [24466] = { name = "Skulldugger's Leggings", source = "The Black Stalker", slot = "Legs", type = "Leather Armor", zone = "The Underbog", reqLevel = 63 },
    [24481] = { name = "Robes of the Augurer", source = "The Black Stalker", slot = "Chest", type = "Cloth Armor", zone = "The Underbog", reqLevel = 63 },
    [27762] = { name = "Weathered Band of the Swamplord", source = "Swamplord Musel'ek", slot = "Finger", type = "Ring", zone = "The Underbog", reqLevel = 70 },
    [27763] = { name = "Crown of the Forest Lord", source = "Swamplord Musel'ek", slot = "Head", type = "Leather Armor", zone = "The Underbog", reqLevel = 70 },
    [27764] = { name = "Hands of the Sun", source = "Swamplord Musel'ek", slot = "Hands", type = "Cloth Armor", zone = "The Underbog", reqLevel = 70 },
    [27765] = { name = "Armwraps of Disdain", source = "Swamplord Musel'ek", slot = "Wrist", type = "Leather Armor", zone = "The Underbog", reqLevel = 70 },
    [27766] = { name = "Swampstone Necklace", source = "Swamplord Musel'ek", slot = "Neck", type = "Amulet", zone = "The Underbog", reqLevel = 70 },
    [27767] = { name = "Bogreaver", source = "Swamplord Musel'ek", slot = "One-Hand", type = "One-Handed Axe", zone = "The Underbog", reqLevel = 70 }
}
SGJ.DungeonDB["ManaTombs_HC"] = {
    [25939] = { name = "Voidfire Wand", source = "Pandemonius", slot = "Ranged", type = "Wand", zone = "Mana-Tombs", reqLevel = 64 },
    [25940] = { name = "Idol of the Claw", source = "Pandemonius", slot = "Relic", type = "Idol", zone = "Mana-Tombs", reqLevel = 64 },
    [25941] = { name = "Boots of the Outlander", source = "Pandemonius", slot = "Feet", type = "Mail Armor", zone = "Mana-Tombs", reqLevel = 64 },
    [25942] = { name = "Faith Bearer's Gauntlets", source = "Pandemonius", slot = "Hands", type = "Plate Armor", zone = "Mana-Tombs", reqLevel = 64 },
    [25943] = { name = "Creepjacker", source = "Pandemonius", slot = "Main Hand", type = "Fist Weapon", zone = "Mana-Tombs", reqLevel = 64 },
    [25944] = { name = "Shaarde the Greater", source = "Tavarok", slot = "Two-Hand", type = "Two-Handed Sword", zone = "Mana-Tombs", reqLevel = 64 },
    [25945] = { name = "Cloak of Revival", source = "Tavarok", slot = "Back", type = "Cloak", zone = "Mana-Tombs", reqLevel = 64 },
    [25946] = { name = "Nethershade Boots", source = "Tavarok", slot = "Feet", type = "Leather Armor", zone = "Mana-Tombs", reqLevel = 64 },
    [25947] = { name = "Lightning-Rod Pauldrons", source = "Tavarok", slot = "Shoulder", type = "Mail Armor", zone = "Mana-Tombs", reqLevel = 64 },
    [25950] = { name = "Staff of Polarities", source = "Tavarok", slot = "Two-Hand", type = "Staff", zone = "Mana-Tombs", reqLevel = 64 },
    [25952] = { name = "Scimitar of the Nexus-Stalkers", source = "Tavarok", slot = "One-Hand", type = "One-Handed Sword", zone = "Mana-Tombs", reqLevel = 64 },
    [25953] = { name = "Ethereal Warp-Bow", source = "Nexus-Prince Shaffar", slot = "Ranged", type = "Bow", zone = "Mana-Tombs", reqLevel = 64 },
    [25954] = { name = "Sigil of Shaffar", source = "Nexus-Prince Shaffar", slot = "Neck", type = "Amulet", zone = "Mana-Tombs", reqLevel = 64 },
    [25955] = { name = "Mask of the Howling Storm", source = "Nexus-Prince Shaffar", slot = "Head", type = "Mail Armor", zone = "Mana-Tombs", reqLevel = 64 },
    [25956] = { name = "Nexus-Bracers of Vigor", source = "Nexus-Prince Shaffar", slot = "Wrist", type = "Plate Armor", zone = "Mana-Tombs", reqLevel = 64 },
    [25957] = { name = "Ethereal Boots of the Skystrider", source = "Nexus-Prince Shaffar", slot = "Feet", type = "Cloth Armor", zone = "Mana-Tombs", reqLevel = 64 },
    [25962] = { name = "Longstrider's Loop", source = "Nexus-Prince Shaffar", slot = "Finger", type = "Ring", zone = "Mana-Tombs", reqLevel = 64 },
    [28166] = { name = "Shield of the Void", source = "Pandemonius", slot = "Shield", type = "Shield", zone = "Mana-Tombs", reqLevel = 64 },
    [27798] = { name = "Gauntlets of Vindication", source = "Nexus-Prince Shaffar", slot = "Hands", type = "Plate Armor", zone = "Mana-Tombs", reqLevel = 70 },
    [27813] = { name = "Boots of the Colossus", source = "Pandemonius", slot = "Feet", type = "Plate Armor", zone = "Mana-Tombs", reqLevel = 70 },
    [27814] = { name = "Twinblade of Mastery", source = "Pandemonius", slot = "One-Hand", type = "Dagger", zone = "Mana-Tombs", reqLevel = 70 },
    [27815] = { name = "Totem of the Astral Winds", source = "Pandemonius", slot = "Relic", type = "Totem", zone = "Mana-Tombs", reqLevel = 70 },
    [27816] = { name = "Mindrage Pauldrons", source = "Pandemonius", slot = "Shoulder", type = "Cloth Armor", zone = "Mana-Tombs", reqLevel = 70 },
    [27817] = { name = "Starbolt Longbow", source = "Pandemonius", slot = "Ranged", type = "Bow", zone = "Mana-Tombs", reqLevel = 70 },
    [27818] = { name = "Starry Robes of the Crescent", source = "Pandemonius", slot = "Chest", type = "Leather Armor", zone = "Mana-Tombs", reqLevel = 70 },
    [27821] = { name = "Extravagant Boots of Malice", source = "Tavarok", slot = "Feet", type = "Cloth Armor", zone = "Mana-Tombs", reqLevel = 70 },
    [27822] = { name = "Crystal Band of Valor", source = "Tavarok", slot = "Finger", type = "Ring", zone = "Mana-Tombs", reqLevel = 70 },
    [27823] = { name = "Shard Encrusted Breastplate", source = "Tavarok", slot = "Chest", type = "Mail Armor", zone = "Mana-Tombs", reqLevel = 70 },
    [27824] = { name = "Robe of the Great Dark Beyond", source = "Tavarok", slot = "Chest", type = "Cloth Armor", zone = "Mana-Tombs", reqLevel = 70 },
    [27825] = { name = "Predatory Gloves", source = "Tavarok", slot = "Hands", type = "Leather Armor", zone = "Mana-Tombs", reqLevel = 70 },
    [27826] = { name = "Mantle of the Sea Wolf", source = "Tavarok", slot = "Shoulder", type = "Mail Armor", zone = "Mana-Tombs", reqLevel = 70 },
    [27827] = { name = "Lucid Dream Bracers", source = "Nexus-Prince Shaffar", slot = "Wrist", type = "Leather Armor", zone = "Mana-Tombs", reqLevel = 70 },
    [27828] = { name = "Warp-Scarab Brooch", source = "Nexus-Prince Shaffar", slot = "Trinket", type = "Trinket", zone = "Mana-Tombs", reqLevel = 70 },
    [27829] = { name = "Axe of the Nexus-Kings", source = "Nexus-Prince Shaffar", slot = "Two-Hand", type = "Two-Handed Axe", zone = "Mana-Tombs", reqLevel = 70 },
    [27831] = { name = "Mantle of the Unforgiven", source = "Nexus-Prince Shaffar", slot = "Shoulder", type = "Leather Armor", zone = "Mana-Tombs", reqLevel = 70 },
    [27835] = { name = "Stillwater Girdle", source = "Nexus-Prince Shaffar", slot = "Waist", type = "Mail Armor", zone = "Mana-Tombs", reqLevel = 70 },
    [27837] = { name = "Wastewalker Leggings", source = "Nexus-Prince Shaffar", slot = "Legs", type = "Leather Armor", zone = "Mana-Tombs", reqLevel = 70 },
    [27840] = { name = "Scepter of Sha'tar", source = "Nexus-Prince Shaffar", slot = "Two-Hand", type = "Two-Handed Mace", zone = "Mana-Tombs", reqLevel = 70 },
    [27842] = { name = "Grand Scepter of the Nexus-Kings", source = "Nexus-Prince Shaffar", slot = "Two-Hand", type = "Staff", zone = "Mana-Tombs", reqLevel = 70 },
    [27843] = { name = "Glyph-Lined Sash", source = "Nexus-Prince Shaffar", slot = "Waist", type = "Cloth Armor", zone = "Mana-Tombs", reqLevel = 70 },
    [27844] = { name = "Pauldrons of Swift Retribution", source = "Nexus-Prince Shaffar", slot = "Shoulder", type = "Plate Armor", zone = "Mana-Tombs", reqLevel = 70 },
    [28400] = { name = "Warp-Storm Warblade", source = "Nexus-Prince Shaffar", slot = "One-Hand", type = "One-Handed Sword", zone = "Mana-Tombs", reqLevel = 70 },
    [29240] = { name = "Bands of Negation", source = "Nexus-Prince Shaffar", slot = "Wrist", type = "Cloth Armor", zone = "Mana-Tombs", reqLevel = 70 },
    [29352] = { name = "Cobalt Band of Tyrigosa", source = "Nexus-Prince Shaffar", slot = "Finger", type = "Ring", zone = "Mana-Tombs", reqLevel = 70 },
    [30535] = { name = "Forestwalker Kilt", source = "Nexus-Prince Shaffar", slot = "Legs", type = "Leather Armor", zone = "Mana-Tombs", reqLevel = 70 },
    [31554] = { name = "Windchanneller's Tunic", source = "Zone Drop", slot = "Chest", type = "Cloth Armor", zone = "Mana-Tombs", reqLevel = 70 },
    [31562] = { name = "Skystalker's Tunic", source = "Zone Drop", slot = "Chest", type = "Leather Armor", zone = "Mana-Tombs", reqLevel = 70 },
    [31570] = { name = "Mistshroud Tunic", source = "Ethereum Prisoner", slot = "Chest", type = "Mail Armor", zone = "Mana-Tombs", reqLevel = 70 },
    [31578] = { name = "Slatesteel Breastplate", source = "Zone Drop", slot = "Chest", type = "Plate Armor", zone = "Mana-Tombs", reqLevel = 70 },
    [31919] = { name = "Nexus-Prince's Ring of Balance", source = "Zone Drop", slot = "Finger", type = "Ring", zone = "Mana-Tombs", reqLevel = 70 },
    [31922] = { name = "Ring of Conflict Survival", source = "Ethereum Prisoner", slot = "Finger", type = "Ring", zone = "Mana-Tombs", reqLevel = 70 },
    [32082] = { name = "The Fel Barrier", source = "Nexus-Prince Shaffar", slot = "Shield", type = "Shield", zone = "Mana-Tombs", reqLevel = 70 }
}
SGJ.DungeonDB["AuchenaiCrypts_HC"] = {
    [25964] = { name = "Shaarde the Lesser", source = "Shirrak the Dead Watcher", slot = "Main Hand", type = "One-Handed Sword", zone = "Auchenai Crypts", reqLevel = 65 },
    [26055] = { name = "Oculus of the Hidden Eye", source = "Shirrak the Dead Watcher", slot = "Trinket", type = "Trinket", zone = "Auchenai Crypts", reqLevel = 65 },
    [27408] = { name = "Hope Bearer Helm", source = "Shirrak the Dead Watcher", slot = "Head", type = "Plate Armor", zone = "Auchenai Crypts", reqLevel = 65 },
    [27409] = { name = "Raven-Heart Headdress", source = "Shirrak the Dead Watcher", slot = "Head", type = "Leather Armor", zone = "Auchenai Crypts", reqLevel = 65 },
    [27410] = { name = "Collar of Command", source = "Shirrak the Dead Watcher", slot = "Head", type = "Cloth Armor", zone = "Auchenai Crypts", reqLevel = 65 },
    [27411] = { name = "Slippers of Serenity", source = "Exarch Maladaar", slot = "Feet", type = "Cloth Armor", zone = "Auchenai Crypts", reqLevel = 65 },
    [27412] = { name = "Ironstaff of Regeneration", source = "Exarch Maladaar", slot = "Two-Hand", type = "Staff", zone = "Auchenai Crypts", reqLevel = 65 },
    [27413] = { name = "Ring of the Exarchs", source = "Exarch Maladaar", slot = "Finger", type = "Ring", zone = "Auchenai Crypts", reqLevel = 65 },
    [27414] = { name = "Mok'Nathal Beast-Mask", source = "Exarch Maladaar", slot = "Head", type = "Mail Armor", zone = "Auchenai Crypts", reqLevel = 65 },
    [27415] = { name = "Darkguard Face Mask", source = "Exarch Maladaar", slot = "Head", type = "Leather Armor", zone = "Auchenai Crypts", reqLevel = 65 },
    [27416] = { name = "Fetish of the Fallen", source = "Exarch Maladaar", slot = "Trinket", type = "Trinket", zone = "Auchenai Crypts", reqLevel = 65 },
    [27493] = { name = "Gloves of the Deadwatcher", source = "Shirrak the Dead Watcher", slot = "Hands", type = "Cloth Armor", zone = "Auchenai Crypts", reqLevel = 70 },
    [27523] = { name = "Exarch's Diamond Band", source = "Exarch Maladaar", slot = "Finger", type = "Ring", zone = "Auchenai Crypts", reqLevel = 70 },
    [27797] = { name = "Wastewalker Shoulderpads", source = "Avatar of the Martyred", slot = "Shoulder", type = "Leather Armor", zone = "Auchenai Crypts", reqLevel = 70 },
    [27845] = { name = "Magma Plume Boots", source = "Shirrak the Dead Watcher", slot = "Feet", type = "Mail Armor", zone = "Auchenai Crypts", reqLevel = 70 },
    [27846] = { name = "Claw of the Watcher", source = "Shirrak the Dead Watcher", slot = "Main Hand", type = "Fist Weapon", zone = "Auchenai Crypts", reqLevel = 70 },
    [27847] = { name = "Fanblade Pauldrons", source = "Shirrak the Dead Watcher", slot = "Shoulder", type = "Plate Armor", zone = "Auchenai Crypts", reqLevel = 70 },
    [27865] = { name = "Bracers of Shirrak", source = "Shirrak the Dead Watcher", slot = "Wrist", type = "Mail Armor", zone = "Auchenai Crypts", reqLevel = 70 },
    [27866] = { name = "Scintillating Headdress of Second Sight", source = "Shirrak the Dead Watcher", slot = "Head", type = "Cloth Armor", zone = "Auchenai Crypts", reqLevel = 70 },
    [27867] = { name = "Boots of the Unjust", source = "Exarch Maladaar", slot = "Feet", type = "Leather Armor", zone = "Auchenai Crypts", reqLevel = 70 },
    [27869] = { name = "Soulpriest's Ring of Resolve", source = "Exarch Maladaar", slot = "Finger", type = "Ring", zone = "Auchenai Crypts", reqLevel = 70 },
    [27870] = { name = "Doomplate Legguards", source = "Exarch Maladaar", slot = "Legs", type = "Plate Armor", zone = "Auchenai Crypts", reqLevel = 70 },
    [27871] = { name = "Maladaar's Blessed Chaplet", source = "Exarch Maladaar", slot = "Neck", type = "Amulet", zone = "Auchenai Crypts", reqLevel = 70 },
    [27872] = { name = "The Harvester of Souls", source = "Exarch Maladaar", slot = "One-Hand", type = "One-Handed Axe", zone = "Auchenai Crypts", reqLevel = 70 },
    [27876] = { name = "Will of the Fallen Exarch", source = "Avatar of the Martyred", slot = "Main Hand", type = "One-Handed Mace", zone = "Auchenai Crypts", reqLevel = 70 },
    [27877] = { name = "Draenic Wildstaff", source = "Avatar of the Martyred", slot = "Two-Hand", type = "Staff", zone = "Auchenai Crypts", reqLevel = 70 },
    [27878] = { name = "Auchenai Death Shroud", source = "Avatar of the Martyred", slot = "Back", type = "Cloak", zone = "Auchenai Crypts", reqLevel = 70 },
    [27937] = { name = "Sky Breaker", source = "Avatar of the Martyred", slot = "Main Hand", type = "One-Handed Mace", zone = "Auchenai Crypts", reqLevel = 68 },
    [28268] = { name = "Natural Mender's Wraps", source = "Avatar of the Martyred", slot = "Hands", type = "Leather Armor", zone = "Auchenai Crypts", reqLevel = 70 },
    [29244] = { name = "Wave-Song Girdle", source = "Exarch Maladaar", slot = "Waist", type = "Mail Armor", zone = "Auchenai Crypts", reqLevel = 70 },
    [29257] = { name = "Sash of Arcane Visions", source = "Exarch Maladaar", slot = "Waist", type = "Cloth Armor", zone = "Auchenai Crypts", reqLevel = 70 },
    [29354] = { name = "Light-Touched Stole of Altruism", source = "Exarch Maladaar", slot = "Back", type = "Cloak", zone = "Auchenai Crypts", reqLevel = 70 }
}
SGJ.DungeonDB["OldHillsbrad_HC"] = {
    [22927] = { name = "Recipe: Ironshield Potion", source = "Captain Skarloc", slot = "None", type = "Alchemy Recipe", zone = "Old Hillsbrad Foothills", reqLevel = 73 },
    [24173] = { name = "Design: Circlet of Arcane Might", source = "Epoch Hunter", slot = "None", type = "Jewelcrafting Design", zone = "Old Hillsbrad Foothills", reqLevel = 74 },
    [27417] = { name = "Ravenwing Pauldrons", source = "Lieutenant Drake", slot = "Shoulder", type = "Leather Armor", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27418] = { name = "Stormreaver Shadow-Kilt", source = "Lieutenant Drake", slot = "Legs", type = "Cloth Armor", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27420] = { name = "Uther's Ceremonial Warboots", source = "Lieutenant Drake", slot = "Feet", type = "Plate Armor", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27423] = { name = "Cloak of Impulsiveness", source = "Lieutenant Drake", slot = "Back", type = "Cloak", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27424] = { name = "Amani Venom-Axe", source = "Captain Skarloc", slot = "One-Hand", type = "One-Handed Axe", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27426] = { name = "Northshire Battlemace", source = "Captain Skarloc", slot = "Main Hand", type = "One-Handed Mace", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27427] = { name = "Durotan's Battle Harness", source = "Captain Skarloc", slot = "Chest", type = "Plate Armor", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27428] = { name = "Stormfront Gauntlets", source = "Captain Skarloc", slot = "Hands", type = "Mail Armor", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27430] = { name = "Scaled Greaves of Patience", source = "Captain Skarloc", slot = "Legs", type = "Mail Armor", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27431] = { name = "Time-Shifted Dagger", source = "Epoch Hunter", slot = "Main Hand", type = "Dagger", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27432] = { name = "Broxigar's Ring of Valor", source = "Epoch Hunter", slot = "Finger", type = "Ring", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27433] = { name = "Pauldrons of Sufferance", source = "Epoch Hunter", slot = "Shoulder", type = "Cloth Armor", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27434] = { name = "Mantle of Perenolde", source = "Epoch Hunter", slot = "Shoulder", type = "Leather Armor", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27436] = { name = "Iron Band of the Unbreakable", source = "Lieutenant Drake", slot = "Finger", type = "Ring", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27440] = { name = "Diamond Prism of Recurrence", source = "Epoch Hunter", slot = "Neck", type = "Amulet", zone = "Old Hillsbrad Foothills", reqLevel = 66 },
    [27904] = { name = "Resounding Ring of Glory", source = "Epoch Hunter", slot = "Finger", type = "Ring", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [27911] = { name = "Epoch's Whispering Cinch", source = "Epoch Hunter", slot = "Waist", type = "Leather Armor", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [28191] = { name = "Mana-Etched Vestments", source = "Epoch Hunter", slot = "Chest", type = "Cloth Armor", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [28210] = { name = "Bloodskull Destroyer", source = "Lieutenant Drake", slot = "One-Hand", type = "One-Handed Mace", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [28211] = { name = "Lieutenant's Signet of Lordaeron", source = "Lieutenant Drake", slot = "Finger", type = "Ring", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [28212] = { name = "Aran's Sorcerous Slacks", source = "Lieutenant Drake", slot = "Legs", type = "Cloth Armor", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [28213] = { name = "Lordaeron Medical Guide", source = "Lieutenant Drake", slot = "Held In Off-hand", type = "Off-hand Frill", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [28214] = { name = "Grips of the Lunar Eclipse", source = "Lieutenant Drake", slot = "Hands", type = "Leather Armor", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [28215] = { name = "Mok'Nathal Mask of Battle", source = "Lieutenant Drake", slot = "Head", type = "Mail Armor", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [28216] = { name = "Dathrohan's Ceremonial Hammer", source = "Captain Skarloc", slot = "Main Hand", type = "One-Handed Mace", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [28217] = { name = "Tarren Mill Vitality Locket", source = "Captain Skarloc", slot = "Neck", type = "Amulet", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [28218] = { name = "Pontiff's Pantaloons of Prophecy", source = "Captain Skarloc", slot = "Legs", type = "Cloth Armor", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [28219] = { name = "Emerald-Scale Greaves", source = "Captain Skarloc", slot = "Legs", type = "Mail Armor", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [28220] = { name = "Moon-Crown Antlers", source = "Captain Skarloc", slot = "Head", type = "Leather Armor", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [28221] = { name = "Boots of the Watchful Heart", source = "Captain Skarloc", slot = "Feet", type = "Plate Armor", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [28222] = { name = "Reaver of the Infinites", source = "Epoch Hunter", slot = "Two-Hand", type = "Two-Handed Axe", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [28223] = { name = "Arcanist's Stone", source = "Epoch Hunter", slot = "Trinket", type = "Trinket", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [28224] = { name = "Wastewalker Helm", source = "Epoch Hunter", slot = "Head", type = "Leather Armor", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [28225] = { name = "Doomplate Warhelm", source = "Epoch Hunter", slot = "Head", type = "Plate Armor", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [28226] = { name = "Timeslicer", source = "Epoch Hunter", slot = "One-Hand", type = "Dagger", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [28227] = { name = "Sparking Arcanite Ring", source = "Epoch Hunter", slot = "Finger", type = "Ring", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [28233] = { name = "Necklace of Resplendent Hope", source = "Epoch Hunter", slot = "Neck", type = "Amulet", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [28344] = { name = "Wyrmfury Pauldrons", source = "Epoch Hunter", slot = "Shoulder", type = "Mail Armor", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [28401] = { name = "Hauberk of Desolation", source = "Epoch Hunter", slot = "Chest", type = "Mail Armor", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [29246] = { name = "Nightfall Wristguards", source = "Epoch Hunter", slot = "Wrist", type = "Leather Armor", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [29250] = { name = "Cord of Sanctification", source = "Epoch Hunter", slot = "Waist", type = "Cloth Armor", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [30534] = { name = "Wyrmscale Greaves", source = "Epoch Hunter", slot = "Legs", type = "Mail Armor", zone = "Old Hillsbrad Foothills", reqLevel = 70 },
    [30536] = { name = "Greaves of the Martyr", source = "Epoch Hunter", slot = "Legs", type = "Plate Armor", zone = "Old Hillsbrad Foothills", reqLevel = 70 }
}
SGJ.DungeonDB["SethekkHalls_HC"] = {
    [27776] = { name = "Shoulderpads of Assassination", source = "Talon King Ikiss", slot = "Shoulder", type = "Leather Armor", zone = "Sethekk Halls", reqLevel = 70 },
    [27838] = { name = "Incanter's Trousers", source = "Talon King Ikiss", slot = "Legs", type = "Cloth Armor", zone = "Sethekk Halls", reqLevel = 70 },
    [27875] = { name = "Hallowed Trousers", source = "Talon King Ikiss", slot = "Legs", type = "Cloth Armor", zone = "Sethekk Halls", reqLevel = 70 },
    [27914] = { name = "Moonstrider Boots", source = "Darkweaver Syth", slot = "Feet", type = "Leather Armor", zone = "Sethekk Halls", reqLevel = 68 },
    [27915] = { name = "Sky-Hunter Swift Boots", source = "Darkweaver Syth", slot = "Feet", type = "Mail Armor", zone = "Sethekk Halls", reqLevel = 68 },
    [27916] = { name = "Sethekk Feather-Darts", source = "Darkweaver Syth", slot = "Thrown", type = "Thrown Weapon", zone = "Sethekk Halls", reqLevel = 68 },
    [27917] = { name = "Libram of the Eternal Rest", source = "Darkweaver Syth", slot = "Relic", type = "Libram", zone = "Sethekk Halls", reqLevel = 68 },
    [27918] = { name = "Bands of Syth", source = "Darkweaver Syth", slot = "Wrist", type = "Plate Armor", zone = "Sethekk Halls", reqLevel = 68 },
    [27919] = { name = "Light-Woven Slippers", source = "Darkweaver Syth", slot = "Feet", type = "Cloth Armor", zone = "Sethekk Halls", reqLevel = 68 },
    [27925] = { name = "Ravenclaw Band", source = "Talon King Ikiss", slot = "Finger", type = "Ring", zone = "Sethekk Halls", reqLevel = 68 },
    [27936] = { name = "Greaves of Desolation", source = "Talon King Ikiss", slot = "Legs", type = "Mail Armor", zone = "Sethekk Halls", reqLevel = 68 },
    [27946] = { name = "Avian Cloak of Feathers", source = "Talon King Ikiss", slot = "Back", type = "Cloak", zone = "Sethekk Halls", reqLevel = 68 },
    [27948] = { name = "Trousers of Oblivion", source = "Talon King Ikiss", slot = "Legs", type = "Cloth Armor", zone = "Sethekk Halls", reqLevel = 68 },
    [27980] = { name = "Terokk's Nightmace", source = "Talon King Ikiss", slot = "One-Hand", type = "One-Handed Mace", zone = "Sethekk Halls", reqLevel = 68 },
    [27981] = { name = "Sethekk Oracle Cloak", source = "Talon King Ikiss", slot = "Back", type = "Cloak", zone = "Sethekk Halls", reqLevel = 68 },
    [27985] = { name = "Deathforge Girdle", source = "Talon King Ikiss", slot = "Waist", type = "Plate Armor", zone = "Sethekk Halls", reqLevel = 68 },
    [27986] = { name = "Crow Wing Reaper", source = "Talon King Ikiss", slot = "Two-Hand", type = "Two-Handed Axe", zone = "Sethekk Halls", reqLevel = 68 },
    [29249] = { name = "Bands of the Benevolent", source = "Talon King Ikiss", slot = "Wrist", type = "Cloth Armor", zone = "Sethekk Halls", reqLevel = 70 },
    [29259] = { name = "Bracers of the Hunt", source = "Talon King Ikiss", slot = "Wrist", type = "Mail Armor", zone = "Sethekk Halls", reqLevel = 70 },
    [29355] = { name = "Terokk's Shadowstaff", source = "Talon King Ikiss", slot = "Two-Hand", type = "Staff", zone = "Sethekk Halls", reqLevel = 70 },
    [32073] = { name = "Spaulders of Dementia", source = "Talon King Ikiss", slot = "Shoulder", type = "Plate Armor", zone = "Sethekk Halls", reqLevel = 70 },
    [32769] = { name = "Belt of the Raven Lord", source = "Anzu", slot = "Waist", type = "Leather Armor", zone = "Sethekk Halls", reqLevel = 70 },
    [32778] = { name = "Boots of Righteous Fortitude", source = "Anzu", slot = "Feet", type = "Plate Armor", zone = "Sethekk Halls", reqLevel = 70 },
    [32779] = { name = "Band of Frigid Elements", source = "Anzu", slot = "Finger", type = "Ring", zone = "Sethekk Halls", reqLevel = 70 },
    [32780] = { name = "The Boomstick", source = "Anzu", slot = "Ranged", type = "Gun", zone = "Sethekk Halls", reqLevel = 70 },
    [32781] = { name = "Talon of Anzu", source = "Anzu", slot = "One-Hand", type = "Dagger", zone = "Sethekk Halls", reqLevel = 70 }
}
SGJ.DungeonDB["BlackMorass_HC"] = {
    [27509] = { name = "Handgrips of Assassination", source = "Aeonus", slot = "Hands", type = "Leather Armor", zone = "The Black Morass", reqLevel = 70 },
    [27839] = { name = "Legplates of the Righteous", source = "Aeonus", slot = "Legs", type = "Plate Armor", zone = "The Black Morass", reqLevel = 70 },
    [27873] = { name = "Moonglade Pants", source = "Aeonus", slot = "Legs", type = "Leather Armor", zone = "The Black Morass", reqLevel = 70 },
    [27977] = { name = "Legplates of the Bold", source = "Aeonus", slot = "Legs", type = "Plate Armor", zone = "The Black Morass", reqLevel = 68 },
    [27987] = { name = "Melmorta's Twilight Longbow", source = "Chrono Lord Deja", slot = "Ranged", type = "Bow", zone = "The Black Morass", reqLevel = 68 },
    [27988] = { name = "Burnoose of Shifting Ages", source = "Chrono Lord Deja", slot = "Back", type = "Cloak", zone = "The Black Morass", reqLevel = 68 },
    [27993] = { name = "Mask of Inner Fire", source = "Chrono Lord Deja", slot = "Head", type = "Mail Armor", zone = "The Black Morass", reqLevel = 68 },
    [27994] = { name = "Mantle of Three Terrors", source = "Chrono Lord Deja", slot = "Shoulder", type = "Cloth Armor", zone = "The Black Morass", reqLevel = 68 },
    [27995] = { name = "Sun-Gilded Shouldercaps", source = "Chrono Lord Deja", slot = "Shoulder", type = "Leather Armor", zone = "The Black Morass", reqLevel = 68 },
    [27996] = { name = "Ring of Spiritual Precision", source = "Chrono Lord Deja", slot = "Finger", type = "Ring", zone = "The Black Morass", reqLevel = 68 },
    [28033] = { name = "Epoch-Mender", source = "Temporus", slot = "Two-Hand", type = "Staff", zone = "The Black Morass", reqLevel = 68 },
    [28034] = { name = "Hourglass of the Unraveller", source = "Temporus", slot = "Trinket", type = "Trinket", zone = "The Black Morass", reqLevel = 68 },
    [28184] = { name = "Millennium Blade", source = "Temporus", slot = "One-Hand", type = "One-Handed Sword", zone = "The Black Morass", reqLevel = 68 },
    [28185] = { name = "Khadgar's Kilt of Abjuration", source = "Temporus", slot = "Legs", type = "Cloth Armor", zone = "The Black Morass", reqLevel = 68 },
    [28186] = { name = "Laughing Skull Battle-Harness", source = "Temporus", slot = "Chest", type = "Mail Armor", zone = "The Black Morass", reqLevel = 68 },
    [28187] = { name = "Star-Heart Lamp", source = "Temporus", slot = "Held In Off-hand", type = "Off-hand Frill", zone = "The Black Morass", reqLevel = 68 },
    [28188] = { name = "Bloodfire Greatstaff", source = "Aeonus", slot = "Two-Hand", type = "Staff", zone = "The Black Morass", reqLevel = 70 },
    [28189] = { name = "Latro's Shifting Sword", source = "Aeonus", slot = "One-Hand", type = "One-Handed Sword", zone = "The Black Morass", reqLevel = 70 },
    [28190] = { name = "Scarab of the Infinite Cycle", source = "Aeonus", slot = "Trinket", type = "Trinket", zone = "The Black Morass", reqLevel = 70 },
    [28192] = { name = "Helm of Desolation", source = "Aeonus", slot = "Head", type = "Mail Armor", zone = "The Black Morass", reqLevel = 70 },
    [28193] = { name = "Mana-Etched Crown", source = "Aeonus", slot = "Head", type = "Cloth Armor", zone = "The Black Morass", reqLevel = 70 },
    [28194] = { name = "Primal Surge Bracers", source = "Aeonus", slot = "Wrist", type = "Mail Armor", zone = "The Black Morass", reqLevel = 70 },
    [28206] = { name = "Cowl of the Guiltless", source = "Aeonus", slot = "Head", type = "Leather Armor", zone = "The Black Morass", reqLevel = 70 },
    [28207] = { name = "Pauldrons of the Crimson Flight", source = "Aeonus", slot = "Shoulder", type = "Plate Armor", zone = "The Black Morass", reqLevel = 70 },
    [29247] = { name = "Girdle of the Deathdealer", source = "Aeonus", slot = "Waist", type = "Leather Armor", zone = "The Black Morass", reqLevel = 70 },
    [29253] = { name = "Girdle of Valorous Deeds", source = "Aeonus", slot = "Waist", type = "Plate Armor", zone = "The Black Morass", reqLevel = 70 },
    [29356] = { name = "Quantum Blade", source = "Aeonus", slot = "Two-Hand", type = "Two-Handed Sword", zone = "The Black Morass", reqLevel = 70 },
    [30558] = { name = "Breeches of the Occultist", source = "Aeonus", slot = "Legs", type = "Cloth Armor", zone = "The Black Morass", reqLevel = 70 }
}
SGJ.DungeonDB["Mechanar_HC"] = {
    [22920] = { name = "Mana Wrath", source = "Pathaleon the Calculator", slot = "Main Hand", type = "One-Handed Sword", zone = "The Mechanar", reqLevel = 70 },
    [27899] = { name = "Moonglade Robe", source = "Pathaleon the Calculator", slot = "Chest", type = "Leather Armor", zone = "The Mechanar", reqLevel = 70 },
    [28202] = { name = "Tunic of Assassination", source = "Pathaleon the Calculator", slot = "Chest", type = "Leather Armor", zone = "The Mechanar", reqLevel = 70 },
    [28204] = { name = "Totem of the Void", source = "Zone Drop", slot = "Relic", type = "Totem", zone = "The Mechanar", reqLevel = 70 },
    [28248] = { name = "Capacitus' Cloak of Calibration", source = "Zone Drop", slot = "Back", type = "Cloak", zone = "The Mechanar", reqLevel = 70 },
    [28249] = { name = "Vestia's Pauldrons of Inner Grace", source = "Zone Drop", slot = "Shoulder", type = "Cloth Armor", zone = "The Mechanar", reqLevel = 70 },
    [28250] = { name = "Boots of the Glade-Keeper", source = "Zone Drop", slot = "Feet", type = "Leather Armor", zone = "The Mechanar", reqLevel = 70 },
    [28251] = { name = "Bloodfyre Robes of Annihilation", source = "Zone Drop", slot = "Chest", type = "Cloth Armor", zone = "The Mechanar", reqLevel = 70 },
    [28252] = { name = "Plasma Rat's Hyper-Scythe", source = "Mechano-Lord Capacitus", slot = "Two-Hand", type = "Polearm", zone = "The Mechanar", reqLevel = 70 },
    [28253] = { name = "Warp Engineer's Prismatic Chain", source = "Mechano-Lord Capacitus", slot = "Neck", type = "Amulet", zone = "The Mechanar", reqLevel = 70 },
    [28254] = { name = "Lunar-Claw Pauldrons", source = "Mechano-Lord Capacitus", slot = "Shoulder", type = "Leather Armor", zone = "The Mechanar", reqLevel = 70 },
    [28255] = { name = "Thoriumweave Cloak", source = "Mechano-Lord Capacitus", slot = "Back", type = "Cloak", zone = "The Mechanar", reqLevel = 70 },
    [28256] = { name = "Hammer of the Penitent", source = "Mechano-Lord Capacitus", slot = "Main Hand", type = "One-Handed Mace", zone = "The Mechanar", reqLevel = 70 },
    [28257] = { name = "Nethershrike", source = "Nethermancer Sepethrea", slot = "Thrown", type = "Thrown Weapon", zone = "The Mechanar", reqLevel = 70 },
    [28258] = { name = "Cosmic Lifeband", source = "Nethermancer Sepethrea", slot = "Finger", type = "Ring", zone = "The Mechanar", reqLevel = 70 },
    [28259] = { name = "Manual of the Nethermancer", source = "Nethermancer Sepethrea", slot = "Held In Off-hand", type = "Off-hand Frill", zone = "The Mechanar", reqLevel = 70 },
    [28260] = { name = "Jade-Skull Breastplate", source = "Nethermancer Sepethrea", slot = "Chest", type = "Plate Armor", zone = "The Mechanar", reqLevel = 70 },
    [28262] = { name = "Stellaris", source = "Nethermancer Sepethrea", slot = "One-Hand", type = "One-Handed Axe", zone = "The Mechanar", reqLevel = 70 },
    [28263] = { name = "Dath'Remar's Ring of Defense", source = "Pathaleon the Calculator", slot = "Finger", type = "Ring", zone = "The Mechanar", reqLevel = 70 },
    [28265] = { name = "Molten Earth Kilt", source = "Pathaleon the Calculator", slot = "Legs", type = "Mail Armor", zone = "The Mechanar", reqLevel = 70 },
    [28266] = { name = "Edge of the Cosmos", source = "Pathaleon the Calculator", slot = "One-Hand", type = "One-Handed Sword", zone = "The Mechanar", reqLevel = 70 },
    [28267] = { name = "Baba's Cloak of Arcanistry", source = "Pathaleon the Calculator", slot = "Back", type = "Cloak", zone = "The Mechanar", reqLevel = 70 },
    [28269] = { name = "Beast Lord Helm", source = "Pathaleon the Calculator", slot = "Head", type = "Mail Armor", zone = "The Mechanar", reqLevel = 70 },
    [28275] = { name = "Incanter's Cowl", source = "Pathaleon the Calculator", slot = "Head", type = "Cloth Armor", zone = "The Mechanar", reqLevel = 70 },
    [28278] = { name = "Helm of the Righteous", source = "Pathaleon the Calculator", slot = "Head", type = "Plate Armor", zone = "The Mechanar", reqLevel = 70 },
    [28285] = { name = "Telescopic Sharprifle", source = "Pathaleon the Calculator", slot = "Ranged", type = "Gun", zone = "The Mechanar", reqLevel = 70 },
    [28288] = { name = "Abacus of Violent Odds", source = "Pathaleon the Calculator", slot = "Trinket", type = "Trinket", zone = "The Mechanar", reqLevel = 70 },
    [29251] = { name = "Boots of the Pious", source = "Pathaleon the Calculator", slot = "Feet", type = "Cloth Armor", zone = "The Mechanar", reqLevel = 70 },
    [29362] = { name = "The Sun Eater", source = "Pathaleon the Calculator", slot = "One-Hand", type = "One-Handed Sword", zone = "The Mechanar", reqLevel = 70 },
    [30533] = { name = "Vanquisher's Legplates", source = "Pathaleon the Calculator", slot = "Legs", type = "Plate Armor", zone = "The Mechanar", reqLevel = 70 },
    [32076] = { name = "Handguards of the Steady", source = "Pathaleon the Calculator", slot = "Hands", type = "Mail Armor", zone = "The Mechanar", reqLevel = 70 }
}
SGJ.DungeonDB["Magisters_HC"] = {
    [34470] = { name = "Timbal's Focusing Crystal", source = "Priestess Delrissa", slot = "Trinket", type = "Trinket", zone = "Magisters' Terrace", reqLevel = 70 },
    [34471] = { name = "Vial of the Sunwell", source = "Priestess Delrissa", slot = "Trinket", type = "Trinket", zone = "Magisters' Terrace", reqLevel = 70 },
    [34472] = { name = "Shard of Contempt", source = "Priestess Delrissa", slot = "Trinket", type = "Trinket", zone = "Magisters' Terrace", reqLevel = 70 },
    [34473] = { name = "Commendation of Kael'thas", source = "Priestess Delrissa", slot = "Trinket", type = "Trinket", zone = "Magisters' Terrace", reqLevel = 70 },
    [34601] = { name = "Shoulderplates of Everlasting Pain", source = "Selin Fireheart", slot = "Shoulder", type = "Plate Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34602] = { name = "Eversong Cuffs", source = "Selin Fireheart", slot = "Wrist", type = "Leather Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34603] = { name = "Distracting Blades", source = "Selin Fireheart", slot = "Thrown", type = "Thrown Weapon", zone = "Magisters' Terrace", reqLevel = 70 },
    [34604] = { name = "Jaded Crystal Dagger", source = "Selin Fireheart", slot = "Main Hand", type = "Dagger", zone = "Magisters' Terrace", reqLevel = 70 },
    [34605] = { name = "Breastplate of Fierce Survival", source = "Vexallus", slot = "Chest", type = "Plate Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34606] = { name = "Edge of Oppression", source = "Vexallus", slot = "One-Hand", type = "Dagger", zone = "Magisters' Terrace", reqLevel = 70 },
    [34607] = { name = "Fel-tinged Mantle", source = "Vexallus", slot = "Shoulder", type = "Cloth Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34608] = { name = "Rod of the Blazing Light", source = "Vexallus", slot = "Two-Hand", type = "Staff", zone = "Magisters' Terrace", reqLevel = 70 },
    [34609] = { name = "Quickening Blade of the Prince", source = "Kael'thas Sunstrider", slot = "One-Hand", type = "One-Handed Sword", zone = "Magisters' Terrace", reqLevel = 70 },
    [34610] = { name = "Scarlet Sin'dorei Robes", source = "Kael'thas Sunstrider", slot = "Chest", type = "Cloth Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34611] = { name = "Cudgel of Consecration", source = "Kael'thas Sunstrider", slot = "Main Hand", type = "One-Handed Mace", zone = "Magisters' Terrace", reqLevel = 70 },
    [34612] = { name = "Greaves of the Penitent Knight", source = "Kael'thas Sunstrider", slot = "Feet", type = "Plate Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34613] = { name = "Shoulderpads of the Silvermoon Retainer", source = "Kael'thas Sunstrider", slot = "Shoulder", type = "Leather Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34614] = { name = "Tunic of the Ranger Lord", source = "Kael'thas Sunstrider", slot = "Chest", type = "Mail Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34615] = { name = "Netherforce Chestplate", source = "Kael'thas Sunstrider", slot = "Chest", type = "Plate Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34616] = { name = "Breeching Comet", source = "Kael'thas Sunstrider", slot = "One-Hand", type = "One-Handed Axe", zone = "Magisters' Terrace", reqLevel = 70 },
    [35275] = { name = "Orb of the Sin'dorei", source = "Boss Drop", slot = "Held In Off-hand", type = "Off-hand Frill", zone = "Magisters' Terrace", reqLevel = 70 },
    [34625] = { name = "Kharmaa's Ring of Fate", source = "Kael'thas Sunstrider", slot = "Finger", type = "Ring", zone = "Magisters' Terrace", reqLevel = 70 },
    [34697] = { name = "Bindings of Raging Fire", source = "Selin Fireheart", slot = "Wrist", type = "Cloth Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34698] = { name = "Bracers of the Forest Stalker", source = "Selin Fireheart", slot = "Wrist", type = "Mail Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34699] = { name = "Sun-forged Cleaver", source = "Selin Fireheart", slot = "One-Hand", type = "One-Handed Axe", zone = "Magisters' Terrace", reqLevel = 70 },
    [34700] = { name = "Gauntlets of Divine Blessings", source = "Selin Fireheart", slot = "Hands", type = "Plate Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34701] = { name = "Leggings of the Betrayed", source = "Selin Fireheart", slot = "Legs", type = "Leather Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34702] = { name = "Cloak of Swift Mending", source = "Selin Fireheart", slot = "Back", type = "Cloak", zone = "Magisters' Terrace", reqLevel = 70 },
    [34703] = { name = "Latro's Dancing Blade", source = "Vexallus", slot = "One-Hand", type = "One-Handed Sword", zone = "Magisters' Terrace", reqLevel = 70 },
    [34704] = { name = "Band of Arcane Alacrity", source = "Vexallus", slot = "Finger", type = "Ring", zone = "Magisters' Terrace", reqLevel = 70 },
    [34705] = { name = "Bracers of Divine Infusion", source = "Vexallus", slot = "Wrist", type = "Cloth Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34706] = { name = "Band of Determination", source = "Vexallus", slot = "Finger", type = "Ring", zone = "Magisters' Terrace", reqLevel = 70 },
    [34707] = { name = "Boots of Resuscitation", source = "Vexallus", slot = "Feet", type = "Leather Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34708] = { name = "Cloak of the Coming Night", source = "Vexallus", slot = "Back", type = "Cloak", zone = "Magisters' Terrace", reqLevel = 70 },
    [34783] = { name = "Nightstrike", source = "Priestess Delrissa", slot = "Thrown", type = "Thrown Weapon", zone = "Magisters' Terrace", reqLevel = 70 },
    [34788] = { name = "Duskhallow Mantle", source = "Priestess Delrissa", slot = "Shoulder", type = "Cloth Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34789] = { name = "Bracers of Slaughter", source = "Priestess Delrissa", slot = "Wrist", type = "Plate Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34790] = { name = "Battle-mace of the High Priestess", source = "Priestess Delrissa", slot = "Main Hand", type = "One-Handed Mace", zone = "Magisters' Terrace", reqLevel = 70 },
    [34791] = { name = "Gauntlets of the Tranquil Waves", source = "Priestess Delrissa", slot = "Hands", type = "Mail Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34792] = { name = "Cloak of the Betrayed", source = "Priestess Delrissa", slot = "Back", type = "Cloak", zone = "Magisters' Terrace", reqLevel = 70 },
    [34793] = { name = "Cord of Reconstruction", source = "Kael'thas Sunstrider", slot = "Waist", type = "Cloth Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34794] = { name = "Axe of Shattered Dreams", source = "Kael'thas Sunstrider", slot = "Two-Hand", type = "Two-Handed Axe", zone = "Magisters' Terrace", reqLevel = 70 },
    [34795] = { name = "Helm of Sanctification", source = "Kael'thas Sunstrider", slot = "Head", type = "Plate Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34796] = { name = "Robes of Summer Flame", source = "Kael'thas Sunstrider", slot = "Chest", type = "Leather Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34797] = { name = "Sun-infused Focus Staff", source = "Kael'thas Sunstrider", slot = "Two-Hand", type = "Staff", zone = "Magisters' Terrace", reqLevel = 70 },
    [34798] = { name = "Band of Celerity", source = "Kael'thas Sunstrider", slot = "Finger", type = "Ring", zone = "Magisters' Terrace", reqLevel = 70 },
    [34799] = { name = "Hauberk of the War Bringer", source = "Kael'thas Sunstrider", slot = "Chest", type = "Mail Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34807] = { name = "Sunstrider Warboots", source = "Kael'thas Sunstrider", slot = "Feet", type = "Plate Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34808] = { name = "Gloves of Arcane Acuity", source = "Kael'thas Sunstrider", slot = "Hands", type = "Cloth Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34809] = { name = "Sunrage Treads", source = "Kael'thas Sunstrider", slot = "Feet", type = "Leather Armor", zone = "Magisters' Terrace", reqLevel = 70 },
    [34810] = { name = "Cloak of Blade Turning", source = "Kael'thas Sunstrider", slot = "Back", type = "Cloak", zone = "Magisters' Terrace", reqLevel = 70 }
}
SGJ.DungeonDB["ShadowLab_HC"] = {
    [24309] = { name = "Moonglade Handwraps", source = "Blackheart the Inciter", slot = "Hands", type = "Leather Armor", zone = "Shadow Labyrinth", reqLevel = 70 },
    [27468] = { name = "Hallowed Pauldrons", source = "Grandmaster Vorpil", slot = "Shoulder", type = "Cloth Armor", zone = "Shadow Labyrinth", reqLevel = 70 },
    [27775] = { name = "Spaulders of Oblivion", source = "Murmur", slot = "Shoulder", type = "Cloth Armor", zone = "Shadow Labyrinth", reqLevel = 70 },
    [27778] = { name = "Shoulderguards of the Bold", source = "Murmur", slot = "Shoulder", type = "Plate Armor", zone = "Shadow Labyrinth", reqLevel = 70 },
    [27884] = { name = "Ornate Boots of the Sanctified", source = "Ambassador Hellmaw", slot = "Feet", type = "Plate Armor", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27885] = { name = "Soul-Wand of the Aldor", source = "Ambassador Hellmaw", slot = "Ranged", type = "Wand", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27886] = { name = "Idol of the Emerald Queen", source = "Ambassador Hellmaw", slot = "Relic", type = "Idol", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27887] = { name = "Platinum Shield of the Valorous", source = "Ambassador Hellmaw", slot = "Shield", type = "Shield", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27888] = { name = "Dream-Wing Helm", source = "Ambassador Hellmaw", slot = "Head", type = "Mail Armor", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27889] = { name = "Jaedenfire Gloves of Annihilation", source = "Ambassador Hellmaw", slot = "Hands", type = "Cloth Armor", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27890] = { name = "Wand of the Netherwing", source = "Blackheart the Inciter", slot = "Ranged", type = "Wand", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27891] = { name = "Adamantine Figurine", source = "Blackheart the Inciter", slot = "Trinket", type = "Trinket", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27892] = { name = "Cloak of the Inciter", source = "Blackheart the Inciter", slot = "Back", type = "Cloak", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27893] = { name = "Ornate Leggings of the Venerated", source = "Blackheart the Inciter", slot = "Legs", type = "Plate Armor", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27897] = { name = "Breastplate of Many Graces", source = "Grandmaster Vorpil", slot = "Chest", type = "Plate Armor", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27898] = { name = "Wrathfire Hand-Cannon", source = "Grandmaster Vorpil", slot = "Ranged", type = "Gun", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27900] = { name = "Jewel of Charismatic Mystique", source = "Grandmaster Vorpil", slot = "Trinket", type = "Trinket", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27901] = { name = "Blackout Truncheon", source = "Grandmaster Vorpil", slot = "One-Hand", type = "One-Handed Mace", zone = "Shadow Labyrinth", reqLevel = 68 },
    [27902] = { name = "Silent Slippers of Meditation", source = "Murmur", slot = "Feet", type = "Cloth Armor", zone = "Shadow Labyrinth", reqLevel = 70 },
    [27903] = { name = "Sonic Spear", source = "Murmur", slot = "Two-Hand", type = "Polearm", zone = "Shadow Labyrinth", reqLevel = 70 },
    [27905] = { name = "Greatsword of Horrid Dreams", source = "Murmur", slot = "Main Hand", type = "One-Handed Sword", zone = "Shadow Labyrinth", reqLevel = 70 },
    [27908] = { name = "Leggings of Assassination", source = "Murmur", slot = "Legs", type = "Leather Armor", zone = "Shadow Labyrinth", reqLevel = 70 },
    [27909] = { name = "Tidefury Kilt", source = "Murmur", slot = "Legs", type = "Mail Armor", zone = "Shadow Labyrinth", reqLevel = 70 },
    [27910] = { name = "Silvermoon Crest Shield", source = "Murmur", slot = "Shield", type = "Shield", zone = "Shadow Labyrinth", reqLevel = 70 },
    [27912] = { name = "Harness of the Deep Currents", source = "Murmur", slot = "Chest", type = "Mail Armor", zone = "Shadow Labyrinth", reqLevel = 70 },
    [27913] = { name = "Whispering Blade of Slaying", source = "Murmur", slot = "One-Hand", type = "Dagger", zone = "Shadow Labyrinth", reqLevel = 70 },
    [28134] = { name = "Brooch of Heightened Potential", source = "Blackheart the Inciter", slot = "Neck", type = "Amulet", zone = "Shadow Labyrinth", reqLevel = 68 },
    [28230] = { name = "Hallowed Garments", source = "Murmur", slot = "Chest", type = "Cloth Armor", zone = "Shadow Labyrinth", reqLevel = 70 },
    [28232] = { name = "Robe of Oblivion", source = "Murmur", slot = "Chest", type = "Cloth Armor", zone = "Shadow Labyrinth", reqLevel = 70 },
    [29261] = { name = "Girdle of Ferocity", source = "Murmur", slot = "Waist", type = "Mail Armor", zone = "Shadow Labyrinth", reqLevel = 70 },
    [29353] = { name = "Shockwave Truncheon", source = "Murmur", slot = "Main Hand", type = "One-Handed Mace", zone = "Shadow Labyrinth", reqLevel = 70 },
    [29357] = { name = "Master Thief's Gloves", source = "Murmur", slot = "Hands", type = "Leather Armor", zone = "Shadow Labyrinth", reqLevel = 70 },
    [30532] = { name = "Kirin Tor Master's Trousers", source = "Murmur", slot = "Legs", type = "Cloth Armor", zone = "Shadow Labyrinth", reqLevel = 70 }
}
SGJ.DungeonDB["Arcatraz_HC"] = {
    [28205] = { name = "Breastplate of the Bold", source = "Zone Drop", slot = "Chest", type = "Plate Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28231] = { name = "Tidefury Chestpiece", source = "Zone Drop", slot = "Chest", type = "Mail Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28372] = { name = "Idol of Feral Shadows", source = "Zereketh the Unbound", slot = "Relic", type = "Idol", zone = "The Arcatraz", reqLevel = 70 },
    [28373] = { name = "Cloak of Scintillating Auras", source = "Zereketh the Unbound", slot = "Back", type = "Cloak", zone = "The Arcatraz", reqLevel = 70 },
    [28374] = { name = "Mana-Sphere Shoulderguards", source = "Zereketh the Unbound", slot = "Shoulder", type = "Cloth Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28375] = { name = "Rubium War-Girdle", source = "Zereketh the Unbound", slot = "Waist", type = "Plate Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28384] = { name = "Outland Striders", source = "Zereketh the Unbound", slot = "Feet", type = "Mail Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28386] = { name = "Nether Core's Control Rod", source = "Dalliah the Doomsayer", slot = "Ranged", type = "Wand", zone = "The Arcatraz", reqLevel = 70 },
    [28387] = { name = "Lamp of Peaceful Repose", source = "Dalliah the Doomsayer", slot = "Held In Off-hand", type = "Off-hand Frill", zone = "The Arcatraz", reqLevel = 70 },
    [28390] = { name = "Thatia's Self-Correcting Gauntlets", source = "Dalliah the Doomsayer", slot = "Hands", type = "Plate Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28391] = { name = "Worldfire Chestguard", source = "Dalliah the Doomsayer", slot = "Chest", type = "Mail Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28392] = { name = "Reflex Blades", source = "Dalliah the Doomsayer", slot = "Main Hand", type = "Fist Weapon", zone = "The Arcatraz", reqLevel = 70 },
    [28393] = { name = "Warmaul of Infused Light", source = "Wrath-Scryer Soccothrates", slot = "Two-Hand", type = "Two-Handed Mace", zone = "The Arcatraz", reqLevel = 70 },
    [28394] = { name = "Ryngo's Band of Ingenuity", source = "Wrath-Scryer Soccothrates", slot = "Finger", type = "Ring", zone = "The Arcatraz", reqLevel = 70 },
    [28396] = { name = "Gloves of the Unbound", source = "Wrath-Scryer Soccothrates", slot = "Hands", type = "Leather Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28397] = { name = "Emberhawk Crossbow", source = "Wrath-Scryer Soccothrates", slot = "Ranged", type = "Crossbow", zone = "The Arcatraz", reqLevel = 70 },
    [28398] = { name = "The Sleeper's Cord", source = "Wrath-Scryer Soccothrates", slot = "Waist", type = "Leather Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28403] = { name = "Doomplate Chestguard", source = "Zone Drop", slot = "Chest", type = "Plate Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28406] = { name = "Sigil-Laced Boots", source = "Zone Drop", slot = "Feet", type = "Cloth Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28407] = { name = "Elementium Band of the Sentry", source = "Zone Drop", slot = "Finger", type = "Ring", zone = "The Arcatraz", reqLevel = 70 },
    [28412] = { name = "Lamp of Peaceful Radiance", source = "Zone Drop", slot = "Held In Off-hand", type = "Off-hand Frill", zone = "The Arcatraz", reqLevel = 70 },
    [28413] = { name = "Hallowed Crown", source = "Zone Drop", slot = "Head", type = "Cloth Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28414] = { name = "Helm of Assassination", source = "Zone Drop", slot = "Head", type = "Leather Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28415] = { name = "Hood of Oblivion", source = "Zone Drop", slot = "Head", type = "Cloth Armor", zone = "The Arcatraz", reqLevel = 70 },
    [28416] = { name = "Hungering Spineripper", source = "Zone Drop", slot = "One-Hand", type = "Dagger", zone = "The Arcatraz", reqLevel = 70 },
    [28418] = { name = "Shiffar's Nexus-Horn", source = "Zone Drop", slot = "Trinket", type = "Trinket", zone = "The Arcatraz", reqLevel = 70 },
    [28419] = { name = "Choker of Fluid Thought", source = "Zone Drop", slot = "Neck", type = "Amulet", zone = "The Arcatraz", reqLevel = 70 },
    [29241] = { name = "Belt of Depravity", source = "Zone Drop", slot = "Waist", type = "Cloth Armor", zone = "The Arcatraz", reqLevel = 70 },
    [29248] = { name = "Shadowstep Striders", source = "Zone Drop", slot = "Feet", type = "Leather Armor", zone = "The Arcatraz", reqLevel = 70 },
    [29252] = { name = "Bracers of Dignity", source = "Zone Drop", slot = "Wrist", type = "Plate Armor", zone = "The Arcatraz", reqLevel = 70 },
    [29360] = { name = "Vileblade of the Betrayer", source = "Zone Drop", slot = "One-Hand", type = "Dagger", zone = "The Arcatraz", reqLevel = 70 }
}
SGJ.DungeonDB["Botanica_HC"] = {
    [27739] = { name = "Spaulders of the Righteous", source = "Laj", slot = "Shoulder", type = "Plate Armor", zone = "The Botanica", reqLevel = 70 },
    [28228] = { name = "Beast Lord Cuirass", source = "Warp Splinter", slot = "Chest", type = "Mail Armor", zone = "The Botanica", reqLevel = 70 },
    [28229] = { name = "Incanter's Robe", source = "Warp Splinter", slot = "Chest", type = "Cloth Armor", zone = "The Botanica", reqLevel = 70 },
    [28296] = { name = "Libram of the Lightbringer", source = "Commander Sarannis", slot = "Relic", type = "Libram", zone = "The Botanica", reqLevel = 70 },
    [28301] = { name = "Syrannis' Mystic Sheen", source = "Commander Sarannis", slot = "Back", type = "Cloak", zone = "The Botanica", reqLevel = 70 },
    [28304] = { name = "Prismatic Mittens of Mending", source = "Commander Sarannis", slot = "Hands", type = "Cloth Armor", zone = "The Botanica", reqLevel = 70 },
    [28306] = { name = "Towering Mantle of the Hunt", source = "Commander Sarannis", slot = "Shoulder", type = "Mail Armor", zone = "The Botanica", reqLevel = 70 },
    [28311] = { name = "Revenger", source = "Commander Sarannis", slot = "One-Hand", type = "One-Handed Sword", zone = "The Botanica", reqLevel = 70 },
    [28315] = { name = "Stormreaver Warblades", source = "High Botanist Freywinn", slot = "Off Hand", type = "Fist Weapon", zone = "The Botanica", reqLevel = 70 },
    [28316] = { name = "Aegis of the Sunbird", source = "High Botanist Freywinn", slot = "Shield", type = "Shield", zone = "The Botanica", reqLevel = 70 },
    [28317] = { name = "Energis Armwraps", source = "High Botanist Freywinn", slot = "Hands", type = "Cloth Armor", zone = "The Botanica", reqLevel = 70 },
    [28318] = { name = "Obsidian Clodstompers", source = "High Botanist Freywinn", slot = "Feet", type = "Plate Armor", zone = "The Botanica", reqLevel = 70 },
    [28321] = { name = "Enchanted Thorium Torque", source = "High Botanist Freywinn", slot = "Neck", type = "Amulet", zone = "The Botanica", reqLevel = 70 },
    [28322] = { name = "Runed Dagger of Solace", source = "Thorngrin the Tender", slot = "Main Hand", type = "Dagger", zone = "The Botanica", reqLevel = 70 },
    [28323] = { name = "Ring of Umbral Doom", source = "Thorngrin the Tender", slot = "Finger", type = "Ring", zone = "The Botanica", reqLevel = 70 },
    [28324] = { name = "Gauntlets of Cruel Intention", source = "Thorngrin the Tender", slot = "Hands", type = "Plate Armor", zone = "The Botanica", reqLevel = 70 },
    [28325] = { name = "Dreamer's Dragonstaff", source = "Thorngrin the Tender", slot = "Two-Hand", type = "Staff", zone = "The Botanica", reqLevel = 70 },
    [28327] = { name = "Arcane Netherband", source = "Thorngrin the Tender", slot = "Finger", type = "Ring", zone = "The Botanica", reqLevel = 70 },
    [28328] = { name = "Mithril-Bark Cloak", source = "Laj", slot = "Back", type = "Cloak", zone = "The Botanica", reqLevel = 70 },
    [28338] = { name = "Devil-Stitched Leggings", source = "Laj", slot = "Legs", type = "Cloth Armor", zone = "The Botanica", reqLevel = 70 },
    [28339] = { name = "Boots of the Shifting Sands", source = "Laj", slot = "Feet", type = "Leather Armor", zone = "The Botanica", reqLevel = 70 },
    [28340] = { name = "Mantle of Autumn", source = "Laj", slot = "Shoulder", type = "Leather Armor", zone = "The Botanica", reqLevel = 70 },
    [28341] = { name = "Warpstaff of Arcanum", source = "Warp Splinter", slot = "Two-Hand", type = "Staff", zone = "The Botanica", reqLevel = 70 },
    [28342] = { name = "Warp Infused Drape", source = "Warp Splinter", slot = "Chest", type = "Cloth Armor", zone = "The Botanica", reqLevel = 70 },
    [28343] = { name = "Jagged Bark Pendant", source = "Warp Splinter", slot = "Neck", type = "Amulet", zone = "The Botanica", reqLevel = 70 },
    [28345] = { name = "Warp Splinter's Thorn", source = "Warp Splinter", slot = "One-Hand", type = "Dagger", zone = "The Botanica", reqLevel = 70 },
    [28347] = { name = "Warpscale Leggings", source = "Warp Splinter", slot = "Legs", type = "Leather Armor", zone = "The Botanica", reqLevel = 70 },
    [28348] = { name = "Moonglade Cowl", source = "Warp Splinter", slot = "Head", type = "Leather Armor", zone = "The Botanica", reqLevel = 70 },
    [28349] = { name = "Tidefury Helm", source = "Warp Splinter", slot = "Head", type = "Mail Armor", zone = "The Botanica", reqLevel = 70 },
    [28350] = { name = "Warhelm of the Bold", source = "Warp Splinter", slot = "Head", type = "Plate Armor", zone = "The Botanica", reqLevel = 70 },
    [28367] = { name = "Greatsword of Forlorn Visions", source = "Warp Splinter", slot = "Two-Hand", type = "Two-Handed Sword", zone = "The Botanica", reqLevel = 70 },
    [28370] = { name = "Bangle of Endless Blessings", source = "Warp Splinter", slot = "Trinket", type = "Trinket", zone = "The Botanica", reqLevel = 70 },
    [28371] = { name = "Netherfury Cape", source = "Warp Splinter", slot = "Back", type = "Cloak", zone = "The Botanica", reqLevel = 70 },
    [29258] = { name = "Boots of Ethereal Manipulation", source = "Warp Splinter", slot = "Feet", type = "Cloth Armor", zone = "The Botanica", reqLevel = 70 },
    [29262] = { name = "Boots of the Endless Hunt", source = "Warp Splinter", slot = "Feet", type = "Mail Armor", zone = "The Botanica", reqLevel = 70 },
    [29359] = { name = "Feral Staff of Lashing", source = "Warp Splinter", slot = "Two-Hand", type = "Staff", zone = "The Botanica", reqLevel = 70 },
    [32072] = { name = "Gauntlets of Dissension", source = "Warp Splinter", slot = "Hands", type = "Plate Armor", zone = "The Botanica", reqLevel = 70 }
}
SGJ.DungeonDB["Steamvault_HC"] = {
    [27475] = { name = "Gauntlets of the Bold", source = "Warlord Kalithresh", slot = "Hands", type = "Plate Armor", zone = "The Steamvault", reqLevel = 70 },
    [27508] = { name = "Incanter's Gloves", source = "Hydromancer Thespia", slot = "Hands", type = "Cloth Armor", zone = "The Steamvault", reqLevel = 70 },
    [27510] = { name = "Tidefury Gauntlets", source = "Warlord Kalithresh", slot = "Hands", type = "Mail Armor", zone = "The Steamvault", reqLevel = 70 },
    [27737] = { name = "Moonglade Shoulders", source = "Warlord Kalithresh", slot = "Shoulder", type = "Leather Armor", zone = "The Steamvault", reqLevel = 70 },
    [27738] = { name = "Incanter's Pauldrons", source = "Warlord Kalithresh", slot = "Shoulder", type = "Cloth Armor", zone = "The Steamvault", reqLevel = 70 },
    [27783] = { name = "Moonrage Girdle", source = "Hydromancer Thespia", slot = "Waist", type = "Leather Armor", zone = "The Steamvault", reqLevel = 68 },
    [27784] = { name = "Scintillating Coral Band", source = "Hydromancer Thespia", slot = "Finger", type = "Ring", zone = "The Steamvault", reqLevel = 68 },
    [27787] = { name = "Chestguard of No Remorse", source = "Hydromancer Thespia", slot = "Chest", type = "Leather Armor", zone = "The Steamvault", reqLevel = 68 },
    [27789] = { name = "Cloak of Whispering Shells", source = "Hydromancer Thespia", slot = "Back", type = "Cloak", zone = "The Steamvault", reqLevel = 68 },
    [27790] = { name = "Mask of Penance", source = "Mekgineer Steamrigger", slot = "Head", type = "Plate Armor", zone = "The Steamvault", reqLevel = 68 },
    [27791] = { name = "Serpentcrest Life-Staff", source = "Mekgineer Steamrigger", slot = "Two-Hand", type = "Staff", zone = "The Steamvault", reqLevel = 68 },
    [27792] = { name = "Steam-Hinge Chain of Valor", source = "Mekgineer Steamrigger", slot = "Neck", type = "Amulet", zone = "The Steamvault", reqLevel = 68 },
    [27793] = { name = "Earth Mantle Handwraps", source = "Mekgineer Steamrigger", slot = "Hands", type = "Mail Armor", zone = "The Steamvault", reqLevel = 68 },
    [27794] = { name = "Recoilless Rocket Ripper X-54", source = "Mekgineer Steamrigger", slot = "Ranged", type = "Gun", zone = "The Steamvault", reqLevel = 68 },
    [27795] = { name = "Sash of Serpentra", source = "Warlord Kalithresh", slot = "Waist", type = "Cloth Armor", zone = "The Steamvault", reqLevel = 70 },
    [27799] = { name = "Vermillion Robes of the Dominant", source = "Warlord Kalithresh", slot = "Chest", type = "Cloth Armor", zone = "The Steamvault", reqLevel = 70 },
    [27801] = { name = "Beast Lord Mantle", source = "Warlord Kalithresh", slot = "Shoulder", type = "Mail Armor", zone = "The Steamvault", reqLevel = 70 },
    [27804] = { name = "Devilshark Cape", source = "Warlord Kalithresh", slot = "Back", type = "Cloak", zone = "The Steamvault", reqLevel = 70 },
    [27805] = { name = "Ring of the Silver Hand", source = "Warlord Kalithresh", slot = "Finger", type = "Ring", zone = "The Steamvault", reqLevel = 70 },
    [27806] = { name = "Fathomheart Gauntlets", source = "Warlord Kalithresh", slot = "Hands", type = "Mail Armor", zone = "The Steamvault", reqLevel = 70 },
    [28203] = { name = "Beast Lord Leggings", source = "Warlord Kalithresh", slot = "Legs", type = "Mail Armor", zone = "The Steamvault", reqLevel = 70 },
    [27874] = { name = "Breastplate of the Righteous", source = "Warlord Kalithresh", slot = "Chest", type = "Plate Armor", zone = "The Steamvault", reqLevel = 70 },
    [29243] = { name = "Wave-Fury Vambraces", source = "Warlord Kalithresh", slot = "Wrist", type = "Mail Armor", zone = "The Steamvault", reqLevel = 70 },
    [29351] = { name = "Wrathtide Longbow", source = "Warlord Kalithresh", slot = "Ranged", type = "Bow", zone = "The Steamvault", reqLevel = 70 },
    [29463] = { name = "Amber Bands of the Aggressor", source = "Warlord Kalithresh", slot = "Wrist", type = "Plate Armor", zone = "The Steamvault", reqLevel = 70 },
    [30550] = { name = "Pontifex Kilt", source = "Warlord Kalithresh", slot = "Legs", type = "Cloth Armor", zone = "The Steamvault", reqLevel = 70 }
}