local addonName, SGJ = ...

SGJ.DungeonDB = SGJ.DungeonDB or {}

-- ============================================================
-- VIRTUAL DUNGEONS
-- Requires adding ["Geras_Badges"] to ZONE_META in Roadmap.lua
-- ============================================================

SGJ.DungeonDB["Geras_Badges"] = {
    [29266] = { name = "Azure-Shield of Coldarra", source = "33 Badges", slot = "Shield", type = "Shield", zone = "G'eras", reqLevel = 70, badgeCost = 33 },
    [29267] = { name = "Light-Bearer's Faith Shield", source = "33 Badges", slot = "Shield", type = "Shield", zone = "G'eras", reqLevel = 70, badgeCost = 33 },
    [29268] = { name = "Mazthoril Honor Shield", source = "33 Badges", slot = "Shield", type = "Shield", zone = "G'eras", reqLevel = 70, badgeCost = 33 },
    [29269] = { name = "Sapphiron's Wing Bone", source = "25 Badges", slot = "Off Hand", type = "Off-hand Frill", zone = "G'eras", reqLevel = 70, badgeCost = 25 },
    [29270] = { name = "Flametongue Seal", source = "25 Badges", slot = "Off Hand", type = "Off-hand Frill", zone = "G'eras", reqLevel = 70, badgeCost = 25 },
    [29271] = { name = "Talisman of Kalecgos", source = "25 Badges", slot = "Off Hand", type = "Off-hand Frill", zone = "G'eras", reqLevel = 70, badgeCost = 25 },
    [29272] = { name = "Orb of the Soul-Eater", source = "25 Badges", slot = "Off Hand", type = "Off-hand Frill", zone = "G'eras", reqLevel = 70, badgeCost = 25 },
    [29273] = { name = "Khadgar's Knapsack", source = "25 Badges", slot = "Off Hand", type = "Off-hand Frill", zone = "G'eras", reqLevel = 70, badgeCost = 25 },
    [29274] = { name = "Tears of Heaven", source = "25 Badges", slot = "Off Hand", type = "Off-hand Frill", zone = "G'eras", reqLevel = 70, badgeCost = 25 },
    [29275] = { name = "Searing Sunblade", source = "50 Badges", slot = "Main Hand", type = "One-Handed Sword", zone = "G'eras", reqLevel = 70, badgeCost = 50 },
    [29367] = { name = "Ring of Cryptic Dreams", source = "25 Badges", slot = "Finger", type = "Ring", zone = "G'eras", reqLevel = 70, badgeCost = 25 },
    [29368] = { name = "Manasurge Pendant", source = "25 Badges", slot = "Neck", type = "Amulet", zone = "G'eras", reqLevel = 70, badgeCost = 25 },
    [29369] = { name = "Shawl of Shifting Probabilities", source = "25 Badges", slot = "Back", type = "Cloak", zone = "G'eras", reqLevel = 70, badgeCost = 25 },
    [29370] = { name = "Icon of the Silver Crescent", source = "41 Badges", slot = "Trinket", type = "Trinket", zone = "G'eras", reqLevel = 70, badgeCost = 41 },
    [29373] = { name = "Band of Halos", source = "25 Badges", slot = "Finger", type = "Ring", zone = "G'eras", reqLevel = 70, badgeCost = 25 },
    [29374] = { name = "Necklace of Eternal Hope", source = "25 Badges", slot = "Neck", type = "Amulet", zone = "G'eras", reqLevel = 70, badgeCost = 25 },
    [29375] = { name = "Bishop's Cloak", source = "25 Badges", slot = "Back", type = "Cloak", zone = "G'eras", reqLevel = 70, badgeCost = 25 },
    [29376] = { name = "Essence of the Martyr", source = "41 Badges", slot = "Trinket", type = "Trinket", zone = "G'eras", reqLevel = 70, badgeCost = 41 },
    [29379] = { name = "Ring of Arathi Warlords", source = "25 Badges", slot = "Finger", type = "Ring", zone = "G'eras", reqLevel = 70, badgeCost = 25 },
    [29381] = { name = "Choker of Vile Intent", source = "25 Badges", slot = "Neck", type = "Amulet", zone = "G'eras", reqLevel = 70, badgeCost = 25 },
    [29382] = { name = "Blood Knight War Cloak", source = "25 Badges", slot = "Back", type = "Cloak", zone = "G'eras", reqLevel = 70, badgeCost = 25 },
    [29383] = { name = "Bloodlust Brooch", source = "41 Badges", slot = "Trinket", type = "Trinket", zone = "G'eras", reqLevel = 70, badgeCost = 41 },
    [29384] = { name = "Ring of Unyielding Force", source = "25 Badges", slot = "Finger", type = "Ring", zone = "G'eras", reqLevel = 70, badgeCost = 25 },
    [29385] = { name = "Farstrider Defender's Cloak", source = "25 Badges", slot = "Back", type = "Cloak", zone = "G'eras", reqLevel = 70, badgeCost = 25 },
    [29386] = { name = "Necklace of the Juggernaut", source = "25 Badges", slot = "Neck", type = "Amulet", zone = "G'eras", reqLevel = 70, badgeCost = 25 },
    [29387] = { name = "Gnomeregan Auto-Blocker 600", source = "41 Badges", slot = "Trinket", type = "Trinket", zone = "G'eras", reqLevel = 70, badgeCost = 41 },
    [29388] = { name = "Libram of Repentance", source = "15 Badges", slot = "Relic", type = "Libram", zone = "G'eras", reqLevel = 70, badgeCost = 15 },
    [29389] = { name = "Totem of the Pulsing Earth", source = "15 Badges", slot = "Relic", type = "Totem", zone = "G'eras", reqLevel = 70, badgeCost = 15 },
    [29390] = { name = "Everbloom Idol", source = "15 Badges", slot = "Relic", type = "Idol", zone = "G'eras", reqLevel = 70, badgeCost = 15 },
    [30183] = { name = "Nether Vortex", source = "15 Badges", slot = "None", type = "Trade Goods", zone = "G'eras", reqLevel = 70, badgeCost = 15 },
    [30761] = { name = "Infernoweave Leggings", source = "30 Badges", slot = "Legs", type = "Cloth Armor", zone = "G'eras", reqLevel = 70, badgeCost = 30 },
    [30762] = { name = "Infernoweave Robe", source = "30 Badges", slot = "Chest", type = "Cloth Armor", zone = "G'eras", reqLevel = 70, badgeCost = 30 },
    [30763] = { name = "Infernoweave Boots", source = "20 Badges", slot = "Feet", type = "Cloth Armor", zone = "G'eras", reqLevel = 70, badgeCost = 20 },
    [30764] = { name = "Infernoweave Gloves", source = "20 Badges", slot = "Hands", type = "Cloth Armor", zone = "G'eras", reqLevel = 70, badgeCost = 20 },
    [30766] = { name = "Inferno Tempered Leggings", source = "30 Badges", slot = "Legs", type = "Mail Armor", zone = "G'eras", reqLevel = 70, badgeCost = 30 },
    [30767] = { name = "Inferno Tempered Gauntlets", source = "20 Badges", slot = "Hands", type = "Mail Armor", zone = "G'eras", reqLevel = 70, badgeCost = 20 },
    [30768] = { name = "Inferno Tempered Boots", source = "20 Badges", slot = "Feet", type = "Mail Armor", zone = "G'eras", reqLevel = 70, badgeCost = 20 },
    [30769] = { name = "Inferno Tempered Chestguard", source = "30 Badges", slot = "Chest", type = "Mail Armor", zone = "G'eras", reqLevel = 70, badgeCost = 30 },
    [30770] = { name = "Inferno Forged Boots", source = "20 Badges", slot = "Feet", type = "Mail Armor", zone = "G'eras", reqLevel = 70, badgeCost = 20 },
    [30772] = { name = "Inferno Forged Leggings", source = "30 Badges", slot = "Legs", type = "Mail Armor", zone = "G'eras", reqLevel = 70, badgeCost = 30 },
    [30773] = { name = "Inferno Forged Hauberk", source = "30 Badges", slot = "Chest", type = "Mail Armor", zone = "G'eras", reqLevel = 70, badgeCost = 30 },
    [30774] = { name = "Inferno Forged Gloves", source = "20 Badges", slot = "Hands", type = "Mail Armor", zone = "G'eras", reqLevel = 70, badgeCost = 20 },
    [30776] = { name = "Inferno Hardened Chestguard", source = "30 Badges", slot = "Chest", type = "Plate Armor", zone = "G'eras", reqLevel = 70, badgeCost = 30 },
    [30778] = { name = "Inferno Hardened Leggings", source = "30 Badges", slot = "Legs", type = "Plate Armor", zone = "G'eras", reqLevel = 70, badgeCost = 30 },
    [30779] = { name = "Inferno Hardened Boots", source = "20 Badges", slot = "Feet", type = "Plate Armor", zone = "G'eras", reqLevel = 70, badgeCost = 20 },
    [30780] = { name = "Inferno Hardened Gloves", source = "20 Badges", slot = "Hands", type = "Plate Armor", zone = "G'eras", reqLevel = 70, badgeCost = 20 },
    [32083] = { name = "Faceguard of Determination", source = "50 Badges", slot = "Head", type = "Plate Armor", zone = "G'eras", reqLevel = 70, badgeCost = 50 },
    [32084] = { name = "Helmet of the Steadfast Champion", source = "50 Badges", slot = "Head", type = "Plate Armor", zone = "G'eras", reqLevel = 70, badgeCost = 50 },
    [32085] = { name = "Warpstalker Helm", source = "50 Badges", slot = "Head", type = "Mail Armor", zone = "G'eras", reqLevel = 70, badgeCost = 50 },
    [32086] = { name = "Storm Master's Helmet", source = "50 Badges", slot = "Head", type = "Mail Armor", zone = "G'eras", reqLevel = 70, badgeCost = 50 },
    [32087] = { name = "Mask of the Deceiver", source = "50 Badges", slot = "Head", type = "Leather Armor", zone = "G'eras", reqLevel = 70, badgeCost = 50 },
    [32088] = { name = "Cowl of Beastly Rage", source = "50 Badges", slot = "Head", type = "Leather Armor", zone = "G'eras", reqLevel = 70, badgeCost = 50 },
    [32089] = { name = "Mana-Binders Cowl", source = "50 Badges", slot = "Head", type = "Cloth Armor", zone = "G'eras", reqLevel = 70, badgeCost = 50 },
    [32090] = { name = "Cowl of Naaru Blessings", source = "50 Badges", slot = "Head", type = "Cloth Armor", zone = "G'eras", reqLevel = 70, badgeCost = 50 },
    [33192] = { name = "Carved Witch Doctor's Stick", source = "25 Badges", slot = "Ranged", type = "Wand", zone = "G'eras", reqLevel = 70, badgeCost = 25 },
    [33207] = { name = "Implacable Guardian Sabatons", source = "60 Badges", slot = "Feet", type = "Plate Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33222] = { name = "Nyn'jah's Tabi Boots", source = "60 Badges", slot = "Feet", type = "Leather Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33279] = { name = "Iron-tusk Girdle", source = "60 Badges", slot = "Waist", type = "Plate Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33280] = { name = "War-Feathered Loop", source = "60 Badges", slot = "Finger", type = "Ring", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33287] = { name = "Gnarled Ironwood Pauldrons", source = "60 Badges", slot = "Shoulder", type = "Plate Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33291] = { name = "Voodoo-woven Belt", source = "60 Badges", slot = "Waist", type = "Cloth Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33296] = { name = "Brooch of Deftness", source = "35 Badges", slot = "Neck", type = "Amulet", zone = "G'eras", reqLevel = 70, badgeCost = 35 },
    [33304] = { name = "Cloak of Subjugated Power", source = "60 Badges", slot = "Back", type = "Cloak", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33324] = { name = "Treads of the Life Path", source = "60 Badges", slot = "Feet", type = "Mail Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33325] = { name = "Voodoo Shaker", source = "35 Badges", slot = "Off Hand", type = "Off-hand Frill", zone = "G'eras", reqLevel = 70, badgeCost = 35 },
    [33331] = { name = "Chain of Unleashed Rage", source = "60 Badges", slot = "Waist", type = "Plate Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33333] = { name = "Kharmaa's Shroud of Hope", source = "60 Badges", slot = "Back", type = "Cloak", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33334] = { name = "Fetish of the Primal Gods", source = "35 Badges", slot = "Off Hand", type = "Off-hand Frill", zone = "G'eras", reqLevel = 70, badgeCost = 35 },
    [33386] = { name = "Man'kin'do's Belt", source = "60 Badges", slot = "Waist", type = "Leather Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33484] = { name = "Dory's Embrace", source = "60 Badges", slot = "Back", type = "Cloak", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33501] = { name = "Bloodthirster's Wargreaves", source = "75 Badges", slot = "Legs", type = "Leather Armor", zone = "G'eras", reqLevel = 70, badgeCost = 75 },
    [33502] = { name = "Libram of Mending", source = "20 Badges", slot = "Relic", type = "Libram", zone = "G'eras", reqLevel = 70, badgeCost = 20 },
    [33503] = { name = "Libram of Divine Judgement", source = "20 Badges", slot = "Relic", type = "Libram", zone = "G'eras", reqLevel = 70, badgeCost = 20 },
    [33504] = { name = "Libram of Divine Purpose", source = "20 Badges", slot = "Relic", type = "Libram", zone = "G'eras", reqLevel = 70, badgeCost = 20 },
    [33505] = { name = "Totem of Living Water", source = "20 Badges", slot = "Relic", type = "Totem", zone = "G'eras", reqLevel = 70, badgeCost = 20 },
    [33506] = { name = "Skycall Totem", source = "20 Badges", slot = "Relic", type = "Totem", zone = "G'eras", reqLevel = 70, badgeCost = 20 },
    [33507] = { name = "Stonebreaker's Totem", source = "20 Badges", slot = "Relic", type = "Totem", zone = "G'eras", reqLevel = 70, badgeCost = 20 },
    [33508] = { name = "Idol of Budding Life", source = "20 Badges", slot = "Relic", type = "Idol", zone = "G'eras", reqLevel = 70, badgeCost = 20 },
    [33509] = { name = "Idol of Terror", source = "20 Badges", slot = "Relic", type = "Idol", zone = "G'eras", reqLevel = 70, badgeCost = 20 },
    [33510] = { name = "Idol of the Unseen Moon", source = "20 Badges", slot = "Relic", type = "Idol", zone = "G'eras", reqLevel = 70, badgeCost = 20 },
    [33512] = { name = "Furious Deathgrips", source = "60 Badges", slot = "Hands", type = "Mail Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33513] = { name = "Eternium Rage-shackles", source = "35 Badges", slot = "Wrist", type = "Plate Armor", zone = "G'eras", reqLevel = 70, badgeCost = 35 },
    [33514] = { name = "Pauldrons of Gruesome Fate", source = "60 Badges", slot = "Shoulder", type = "Plate Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33515] = { name = "Unwavering Legguards", source = "75 Badges", slot = "Legs", type = "Plate Armor", zone = "G'eras", reqLevel = 70, badgeCost = 75 },
    [33516] = { name = "Bracers of the Ancient Phalanx", source = "35 Badges", slot = "Wrist", type = "Plate Armor", zone = "G'eras", reqLevel = 70, badgeCost = 35 },
    [33517] = { name = "Bonefist Gauntlets", source = "60 Badges", slot = "Hands", type = "Plate Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33518] = { name = "High Justicar's Legplates", source = "75 Badges", slot = "Legs", type = "Plate Armor", zone = "G'eras", reqLevel = 70, badgeCost = 75 },
    [33519] = { name = "Handguards of the Templar", source = "60 Badges", slot = "Hands", type = "Plate Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33520] = { name = "Vambraces of the Naaru", source = "35 Badges", slot = "Wrist", type = "Plate Armor", zone = "G'eras", reqLevel = 70, badgeCost = 35 },
    [33522] = { name = "Chestguard of the Stoic Guardian", source = "75 Badges", slot = "Chest", type = "Plate Armor", zone = "G'eras", reqLevel = 70, badgeCost = 75 },
    [33523] = { name = "Sabatons of the Righteous Defender", source = "60 Badges", slot = "Feet", type = "Plate Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33524] = { name = "Girdle of the Protector", source = "60 Badges", slot = "Waist", type = "Plate Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33527] = { name = "Shifting Camouflage Pants", source = "75 Badges", slot = "Legs", type = "Leather Armor", zone = "G'eras", reqLevel = 70, badgeCost = 75 },
    [33528] = { name = "Gauntlets of Sniping", source = "60 Badges", slot = "Hands", type = "Mail Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33529] = { name = "Steadying Bracers", source = "35 Badges", slot = "Wrist", type = "Mail Armor", zone = "G'eras", reqLevel = 70, badgeCost = 35 },
    [33530] = { name = "Natural Life Leggings", source = "75 Badges", slot = "Legs", type = "Leather Armor", zone = "G'eras", reqLevel = 70, badgeCost = 75 },
    [33531] = { name = "Polished Waterscale Gloves", source = "60 Badges", slot = "Hands", type = "Mail Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33532] = { name = "Gleaming Earthen Bracers", source = "35 Badges", slot = "Wrist", type = "Mail Armor", zone = "G'eras", reqLevel = 70, badgeCost = 35 },
    [33534] = { name = "Grips of Nature's Wrath", source = "60 Badges", slot = "Hands", type = "Leather Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33535] = { name = "Earthquake Bracers", source = "35 Badges", slot = "Wrist", type = "Mail Armor", zone = "G'eras", reqLevel = 70, badgeCost = 35 },
    [33536] = { name = "Stormwrap", source = "60 Badges", slot = "Chest", type = "Mail Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33537] = { name = "Treads of Booming Thunder", source = "60 Badges", slot = "Feet", type = "Mail Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33538] = { name = "Shallow-grave Trousers", source = "75 Badges", slot = "Legs", type = "Cloth Armor", zone = "G'eras", reqLevel = 70, badgeCost = 75 },
    [33539] = { name = "Trickster's Stickyfingers", source = "60 Badges", slot = "Hands", type = "Leather Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33540] = { name = "Master Assassin Wristwraps", source = "35 Badges", slot = "Wrist", type = "Leather Armor", zone = "G'eras", reqLevel = 70, badgeCost = 35 },
    [33552] = { name = "Pants of Splendid Recovery", source = "75 Badges", slot = "Legs", type = "Cloth Armor", zone = "G'eras", reqLevel = 70, badgeCost = 75 },
    [33557] = { name = "Gargon's Bracers of Peaceful Slumber", source = "35 Badges", slot = "Wrist", type = "Cloth Armor", zone = "G'eras", reqLevel = 70, badgeCost = 35 },
    [33559] = { name = "Starfire Waistband", source = "60 Badges", slot = "Waist", type = "Cloth Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33566] = { name = "Blessed Elunite Coverings", source = "75 Badges", slot = "Legs", type = "Leather Armor", zone = "G'eras", reqLevel = 70, badgeCost = 75 },
    [33577] = { name = "Moon-walkers", source = "60 Badges", slot = "Feet", type = "Leather Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33578] = { name = "Armwraps of the Kaldorei Protector", source = "35 Badges", slot = "Wrist", type = "Leather Armor", zone = "G'eras", reqLevel = 70, badgeCost = 35 },
    [33579] = { name = "Vestments of Hibernation", source = "75 Badges", slot = "Chest", type = "Leather Armor", zone = "G'eras", reqLevel = 70, badgeCost = 75 },
    [33580] = { name = "Band of the Swift Paw", source = "35 Badges", slot = "Finger", type = "Ring", zone = "G'eras", reqLevel = 70, badgeCost = 35 },
    [33582] = { name = "Footwraps of Wild Encroachment", source = "60 Badges", slot = "Feet", type = "Leather Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33583] = { name = "Waistguard of the Great Beast", source = "60 Badges", slot = "Waist", type = "Leather Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33584] = { name = "Pantaloons of Arcane Annihilation", source = "75 Badges", slot = "Legs", type = "Cloth Armor", zone = "G'eras", reqLevel = 70, badgeCost = 75 },
    [33585] = { name = "Achromic Trousers of the Naaru", source = "75 Badges", slot = "Legs", type = "Cloth Armor", zone = "G'eras", reqLevel = 70, badgeCost = 75 },
    [33586] = { name = "Studious Wraps", source = "60 Badges", slot = "Hands", type = "Cloth Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33587] = { name = "Light-Blessed Bonds", source = "60 Badges", slot = "Wrist", type = "Cloth Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33588] = { name = "Runed Spell-cuffs", source = "35 Badges", slot = "Wrist", type = "Cloth Armor", zone = "G'eras", reqLevel = 70, badgeCost = 35 },
    [33589] = { name = "Wristguards of Tranquil Thought", source = "35 Badges", slot = "Wrist", type = "Cloth Armor", zone = "G'eras", reqLevel = 70, badgeCost = 35 },
    [33593] = { name = "Slikk's Cloak of Placation", source = "35 Badges", slot = "Back", type = "Cloak", zone = "G'eras", reqLevel = 70, badgeCost = 35 },
    [33810] = { name = "Amani Mask of Death", source = "75 Badges", slot = "Head", type = "Leather Armor", zone = "G'eras", reqLevel = 70, badgeCost = 75 },
    [33832] = { name = "Battlemaster's Determination", source = "75 Badges", slot = "Trinket", type = "Trinket", zone = "G'eras", reqLevel = 70, badgeCost = 75 },
    [33965] = { name = "Hauberk of the Furious Elements", source = "75 Badges", slot = "Chest", type = "Mail Armor", zone = "G'eras", reqLevel = 70, badgeCost = 75 },
    [33970] = { name = "Pauldrons of the Furious Elements", source = "60 Badges", slot = "Shoulder", type = "Mail Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33972] = { name = "Mask of Primal Power", source = "75 Badges", slot = "Head", type = "Mail Armor", zone = "G'eras", reqLevel = 70, badgeCost = 75 },
    [33973] = { name = "Pauldrons of Tribal Fury", source = "60 Badges", slot = "Shoulder", type = "Mail Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [33974] = { name = "Grasp of the Moonkin Hands", source = "60 Badges", slot = "Hands", type = "Leather Armor", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [34049] = { name = "Battlemaster's Audacity", source = "75 Badges", slot = "Trinket", type = "Trinket", zone = "G'eras", reqLevel = 70, badgeCost = 75 },
    [34050] = { name = "Battlemaster's Perseverance", source = "75 Badges", slot = "Trinket", type = "Trinket", zone = "G'eras", reqLevel = 70, badgeCost = 75 },
    [34162] = { name = "Battlemaster's Depravity", source = "75 Badges", slot = "Trinket", type = "Trinket", zone = "G'eras", reqLevel = 70, badgeCost = 75 },
    [34163] = { name = "Battlemaster's Cruelty", source = "75 Badges", slot = "Trinket", type = "Trinket", zone = "G'eras", reqLevel = 70, badgeCost = 75 },
    [35321] = { name = "Cloak of Arcane Alacrity", source = "60 Badges", slot = "Back", type = "Cloak", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [35324] = { name = "Cloak of Swift Reprieve", source = "60 Badges", slot = "Back", type = "Cloak", zone = "G'eras", reqLevel = 70, badgeCost = 60 },
    [35326] = { name = "Battlemaster's Alacrity", source = "75 Badges", slot = "Trinket", type = "Trinket", zone = "G'eras", reqLevel = 70, badgeCost = 75 }
}